# Form implementation generated from reading ui file '.\ui\editSettingsContextMenu.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        Form.setAcceptDrops(False)
        Form.setStyleSheet("QMenu::item { \n"
"font-size: 16px; }\n"
"QAction {\n"
"icon-size: 17px;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.actionShow_Workspace_Grid = QtGui.QAction(parent=Form)
        self.actionShow_Workspace_Grid.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../../resources/icons/toggle-button-off.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../../resources/icons/toggle-button-on.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.actionShow_Workspace_Grid.setIcon(icon)
        self.actionShow_Workspace_Grid.setObjectName("actionShow_Workspace_Grid")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.actionShow_Workspace_Grid.setText(_translate("Form", "Show Workspace Grid"))
