# Form implementation generated from reading ui file 'src/ui/measure_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(477, 535)
        Dialog.setStyleSheet("background-color: rgb(20, 20, 20); \n"
"border-radius: 5px;\n"
"border: 0px;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 5px;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(5, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        self.label_2.setStyleSheet("font: 623 14pt \"Segoe UI\";\n"
"color: rgb(233, 233, 233);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_4.setStyleSheet("color:white;\n"
"border-radius: 5px;\n"
"background-color: rgb(35, 35, 35);")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.widget_4)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"  border: 3px solid rgb(55, 55, 55);\n"
"  color: #64B2D1;\n"
"  border-radius: 5px;\n"
"}\n"
"QGroupBox:disabled{\n"
"    color: rgb(55, 55, 55);\n"
"}")
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setContentsMargins(5, 15, 5, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fileName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.fileName.setMinimumSize(QtCore.QSize(35, 35))
        self.fileName.setStyleSheet("border: 0px;\n"
"        font: 700 10pt \"Segoe UI\";\n"
"         background: rgb(55, 55, 55);\n"
"        border :3px solid rgb(55, 55, 55);\n"
"color: rgb(94, 94, 94)")
        self.fileName.setObjectName("fileName")
        self.verticalLayout_6.addWidget(self.fileName)
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.checkBox.setEnabled(True)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    font: 550 10pt \"Segoe UI\";\n"
"    color: rgb(94, 94, 94);\n"
"}\n"
"QCheckBox::checked {\n"
"    font: 550 10pt \"Segoe UI\";\n"
"    color: rgb(233, 233, 233);\n"
"}\n"
"QCheckBox::hover\n"
"{\n"
"    background-color : rgb(0, 0, 0);\n"
"    border: 0;\n"
"}\n"
"QCheckBox::indicator{\n"
"width :35px;\n"
"height : 35px;\n"
"}\n"
"QCheckBox::indicator:checked\n"
" {\n"
"     image: url(../resources/icons/toggle-button-on.png);\n"
"}\n"
"  QCheckBox::indicator:unchecked\n"
"{\n"
"    image: url(../resources/icons/toggle-button-off.png);\n"
"}")
        self.checkBox.setIconSize(QtCore.QSize(45, 45))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        self.line = QtWidgets.QFrame(parent=self.groupBox_2)
        self.line.setStyleSheet("background-color: rgba(129, 129, 129, 50);\n"
"border: 0px;\n"
"border-radius: 50%;\n"
"margin: 5, 5, 5, 5;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.checkBox_2.setAutoFillBackground(False)
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"    font: 550 10pt \"Segoe UI\";\n"
"    color: rgb(94, 94, 94);\n"
"}\n"
"QCheckBox::checked {\n"
"    font: 550 10pt \"Segoe UI\";\n"
"    color: rgb(233, 233, 233);\n"
"}\n"
"QCheckBox::hover\n"
"{\n"
"    background-color : rgb(0, 0, 0);\n"
"    border: 0;\n"
"}\n"
"QCheckBox::indicator{\n"
"width :35px;\n"
"height : 35px;\n"
"}\n"
"QCheckBox::indicator:checked\n"
" {\n"
"     image: url(../resources/icons/toggle-button-on.png);\n"
"}\n"
"  QCheckBox::indicator:unchecked\n"
"{\n"
"    image: url(../resources/icons/toggle-button-off.png);\n"
"}")
        self.checkBox_2.setIconSize(QtCore.QSize(45, 45))
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setAutoRepeat(False)
        self.checkBox_2.setAutoExclusive(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_6.addWidget(self.checkBox_2)
        self.line_2 = QtWidgets.QFrame(parent=self.groupBox_2)
        self.line_2.setStyleSheet("background-color: rgba(129, 129, 129, 50);\n"
"border: 0px;\n"
"border-radius: 50%;\n"
"margin: 5, 5, 5, 5;")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox_3.setAutoFillBackground(False)
        self.checkBox_3.setStyleSheet("QCheckBox {\n"
"    font: 550 10pt \"Segoe UI\";\n"
"    color: rgb(94, 94, 94);\n"
"}\n"
"QCheckBox::checked {\n"
"    font: 550 10pt \"Segoe UI\";\n"
"    color: rgb(233, 233, 233);\n"
"}\n"
"QCheckBox::hover\n"
"{\n"
"    background-color : rgb(0, 0, 0);\n"
"    border: 0;\n"
"}\n"
"QCheckBox::indicator{\n"
"width :35px;\n"
"height : 35px;\n"
"}\n"
"QCheckBox::indicator:checked\n"
" {\n"
"     image: url(../resources/icons/toggle-button-on.png);\n"
"}\n"
"  QCheckBox::indicator:unchecked\n"
"{\n"
"    image: url(../resources/icons/toggle-button-off.png);\n"
"}")
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_6.addWidget(self.checkBox_3)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_5.setContentsMargins(0, 2, 2, 2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_5.setMaximumSize(QtCore.QSize(20, 20))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("src/ui/../../resources/icons/save-diskette.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(parent=self.widget_8)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setStyleSheet("font: 600 11pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.gridLayout.addWidget(self.widget_8, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_5.setStyleSheet("color:white;\n"
"border-radius: 5px;\n"
"background-color: rgb(35, 35, 35);")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setContentsMargins(0, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("src/ui/../../resources/icons/chronometer.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_3.setStyleSheet("font: 600 11pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.widget_6)
        self.checkBox_5.setMaximumSize(QtCore.QSize(35, 35))
        self.checkBox_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox_5.setStyleSheet("QCheckBox {\n"
"    font: 550 10pt \"Segoe UI\";\n"
"    color: rgb(94, 94, 94);\n"
"}\n"
"QCheckBox::checked {\n"
"    font: 550 10pt \"Segoe UI\";\n"
"    color: rgb(233, 233, 233);\n"
"}\n"
"QCheckBox::hover\n"
"{\n"
"    border: 0;\n"
"}\n"
"QCheckBox::indicator{\n"
"width :17px;\n"
"height : 17px;\n"
"}\n"
"QCheckBox::indicator:checked\n"
" {\n"
"     image: url(../resources/icons/padlock-unlock.png);\n"
"}\n"
"  QCheckBox::indicator:unchecked\n"
"{\n"
"    image: url(../resources/icons/padlock.png);\n"
"}")
        self.checkBox_5.setText("")
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_3.addWidget(self.checkBox_5)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(parent=self.widget_9)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"  border: 3px solid rgb(55, 55, 55);\n"
"  color: #64B2D1;\n"
"  border-radius: 5px;\n"
"}\n"
"QGroupBox:disabled{\n"
"    color: rgb(55, 55, 55);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setContentsMargins(5, 15, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_10 = QtWidgets.QWidget(parent=self.groupBox)
        self.widget_10.setStyleSheet("QSpinBox\n"
"{\n"
"border: 0px;\n"
"        font: 700 10pt \"Segoe UI\";\n"
"         background: rgb(55, 55, 55);\n"
"        border :3px solid rgb(55, 55, 55);\n"
"color: rgb(94, 94, 94)\n"
"}\n"
"QDoubleSpinBox::up-arrow\n"
"{\n"
"}\n"
"QDoubleSpinBox::down-arrow\n"
"{\n"
"}")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_2.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.widget_10)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(0, 35))
        self.doubleSpinBox.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border: 0px;\n"
"        font: 700 10pt \"Segoe UI\";\n"
"         background: rgb(55, 55, 55);\n"
"        border :3px solid rgb(55, 55, 55);\n"
"color: rgb(94, 94, 94)\n"
"}\n"
"QDoubleSpinBox::up-arrow\n"
"{\n"
"}\n"
"QDoubleSpinBox::down-arrow\n"
"{\n"
"}")
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setSpecialValueText("")
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(parent=self.widget_10)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 35))
        self.spinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBox.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border: 0px;\n"
"        font: 700 10pt \"Segoe UI\";\n"
"         background: rgb(55, 55, 55);\n"
"        border :3px solid rgb(55, 55, 55);\n"
"color: rgb(94, 94, 94)\n"
"}")
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.widget_10)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.widget_9)
        self.verticalLayout_3.addWidget(self.widget_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_7.setStyleSheet("color:white;\n"
"border-radius: 5px;\n"
"background-color: rgb(35, 35, 35);")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 700 10pt \"Segoe UI\";\n"
"        border :1.5px solid rgb(55, 55, 55);\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        background-color: rgb(45, 45, 45);\n"
"}\n"
"QPushTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 700 10pt \"Segoe UI\";\n"
"         background: rgb(55, 55, 55);\n"
"        border :3px solid rgb(55, 55, 55);\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(43, 81, 235);\n"
"            border :3px solid rgb(63, 101, 255);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        background: rgb(43, 81, 235);\n"
"        border :3px solid rgb(63, 101, 255);\n"
"}\n"
"QPushTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        self.pushButton_6.clicked.connect(Dialog.onAccept) # type: ignore
        self.pushButton_5.clicked.connect(Dialog.reject) # type: ignore
        self.checkBox_5.toggled['bool'].connect(self.groupBox.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.widget.setStyleSheet(_translate("Dialog", "0"))
        self.label_2.setText(_translate("Dialog", "New Measurement"))
        self.groupBox_2.setTitle(_translate("Dialog", "Fill out the options to save the measurement"))
        self.fileName.setPlaceholderText(_translate("Dialog", "File name"))
        self.checkBox.setText(_translate("Dialog", "Measurement Conditions"))
        self.checkBox_2.setText(_translate("Dialog", "Spectral Data"))
        self.checkBox_3.setText(_translate("Dialog", "Colorimetric Data"))
        self.label.setText(_translate("Dialog", "Save file"))
        self.label_3.setText(_translate("Dialog", "Timer"))
        self.groupBox.setTitle(_translate("Dialog", "The measurement will start following this time"))
        self.doubleSpinBox.setSuffix(_translate("Dialog", " sec"))
        self.spinBox.setSuffix(_translate("Dialog", " times"))
        self.pushButton_5.setText(_translate("Dialog", "Cancel"))
        self.pushButton_6.setText(_translate("Dialog", "Start"))

