# Form implementation generated from reading ui file 'ui/measure_dialog_prot.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(683, 795)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(20,20,20)")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 55))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: grey;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setStyleSheet("background-color: rgb(31,31,31);\n"
"border: 1px solid rgb(60,60,60);/* Szegély a jobb elválasztásért */\n"
"border-radius: 5px; ")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_8.setStyleSheet("border: 0px;")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 0px;\n"
"color: rgb(200,200,200);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.widget_8)
        self.widget_14 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_14.setStyleSheet("border: 0px;")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_13.setSpacing(20)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.line = QtWidgets.QFrame(parent=self.widget_14)
        self.line.setStyleSheet("background-color: rgb(40,40,40);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_13.addWidget(self.line)
        self.label_9 = QtWidgets.QLabel(parent=self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: 0px;\n"
"color: rgb(200,200,200);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.widget_17 = QtWidgets.QWidget(parent=self.widget_14)
        self.widget_17.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_17)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(40,40,40); color: grey;")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_17)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setUnderline(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color:  #6c757d; \n"
"color: #dee2e6;  \n"
"border: 1px solid #adb5bd;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_13.addWidget(self.widget_17)
        self.verticalLayout_4.addWidget(self.widget_14)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_5.setStyleSheet("border: 0px;")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setContentsMargins(9, 15, 9, 15)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0,145, 245);\n"
"    color: white;              \n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #C0C0C0;\n"
"    color: #808080;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../Dokumentumok/PE_Spectroradiometer/PE_Spectroradiometer/resources/icons/play-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_6.setStyleSheet("border: 0px;")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_11 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_6.setMinimumSize(QtCore.QSize(40, 40))
        self.label_6.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("/*\n"
" * Függőben lévő (pending) állapot\n"
" * Szürke háttér, halvány szöveg.\n"
" */\n"
"QLabel {\n"
"    background-color: #6c757d; /* Sötétszürke háttér */\n"
"    color: #dee2e6;           /* Világosszürke szöveg */\n"
"    border: 1px solid #adb5bd;/* Szegély a jobb elválasztásért */\n"
"    border-radius: 20px;      /* Kerekítjük a sarkokat (körhöz 50% kell) */\n"
"    padding: 8px;             /* Kisebb belső térköz */\n"
"}\n"
"#label_6[state=\"idle\"] {\n"
"    color: #dee2e6; \n"
"    background-color: #6c757d;\n"
"    font-weight: bold;\n"
"}\n"
"#label_6[state=\"in-progress\"] {\n"
"    background-color: rgb(0,145,245);\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_6[state=\"done\"] {\n"
"    background-color: #008000; /* Zöld */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_6[state=\"failed\"] {\n"
"    background-color: #FF0000; /* Piros */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}")
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_18 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_18.setStyleSheet("color: grey;")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.horizontalLayout_3.addWidget(self.widget_11, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_13 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_13)
        self.label_7.setMinimumSize(QtCore.QSize(40, 40))
        self.label_7.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("/*\n"
" * Függőben lévő (pending) állapot\n"
" * Szürke háttér, halvány szöveg.\n"
" */\n"
"QLabel {\n"
"    background-color: #6c757d; /* Sötétszürke háttér */\n"
"    color: #dee2e6;           /* Világosszürke szöveg */\n"
"    border: 1px solid #adb5bd;/* Szegély a jobb elválasztásért */\n"
"    border-radius: 20px;      /* Kerekítjük a sarkokat (körhöz 50% kell) */\n"
"    padding: 8px;             /* Kisebb belső térköz */\n"
"}\n"
"#label_7[state=\"idle\"] {\n"
"    color: #dee2e6; \n"
"    background-color: #6c757d;\n"
"    font-weight: bold;\n"
"}\n"
"#label_7[state=\"in-progress\"] {\n"
"    background-color: rgb(0,145,245);\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_7[state=\"done\"] {\n"
"    background-color: #008000; /* Zöld */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_7[state=\"failed\"] {\n"
"    background-color: #FF0000; /* Piros */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}")
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_19 = QtWidgets.QLabel(parent=self.widget_13)
        self.label_19.setStyleSheet("color: grey;")
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_11.addWidget(self.label_19)
        self.horizontalLayout_3.addWidget(self.widget_13, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_12 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_12)
        self.label_8.setMinimumSize(QtCore.QSize(40, 40))
        self.label_8.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("/*\n"
" * Függőben lévő (pending) állapot\n"
" * Szürke háttér, halvány szöveg.\n"
" */\n"
"QLabel {\n"
"    background-color: #6c757d; /* Sötétszürke háttér */\n"
"    color: #dee2e6;           /* Világosszürke szöveg */\n"
"    border: 1px solid #adb5bd;/* Szegély a jobb elválasztásért */\n"
"    border-radius: 20px;      /* Kerekítjük a sarkokat (körhöz 50% kell) */\n"
"    padding: 8px;             /* Kisebb belső térköz */\n"
"}\n"
"#label_8[state=\"idle\"] {\n"
"    color: #dee2e6; \n"
"    background-color: #6c757d;\n"
"    font-weight: bold;\n"
"}\n"
"#label_8[state=\"in-progress\"] {\n"
"    background-color: rgb(0,145,245);\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_8[state=\"done\"] {\n"
"    background-color: #008000; /* Zöld */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_8[state=\"failed\"] {\n"
"    background-color: #FF0000; /* Piros */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}")
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_23 = QtWidgets.QLabel(parent=self.widget_12)
        self.label_23.setStyleSheet("color: grey;")
        self.label_23.setWordWrap(False)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.horizontalLayout_3.addWidget(self.widget_12, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_15 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_15)
        self.label_10.setMinimumSize(QtCore.QSize(40, 40))
        self.label_10.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("/*\n"
" * Függőben lévő (pending) állapot\n"
" * Szürke háttér, halvány szöveg.\n"
" */\n"
"QLabel {\n"
"    background-color: #6c757d; /* Sötétszürke háttér */\n"
"    color: #dee2e6;           /* Világosszürke szöveg */\n"
"    border: 1px solid #adb5bd;/* Szegély a jobb elválasztásért */\n"
"    border-radius: 20px;      /* Kerekítjük a sarkokat (körhöz 50% kell) */\n"
"    padding: 8px;             /* Kisebb belső térköz */\n"
"}\n"
"#label_10[state=\"idle\"] {\n"
"    color: #dee2e6; \n"
"    background-color: #6c757d;\n"
"    font-weight: bold;\n"
"}\n"
"#label_10[state=\"in-progress\"] {\n"
"    background-color: rgb(0,145,245);\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_10[state=\"done\"] {\n"
"    background-color: #008000; /* Zöld */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_10[state=\"failed\"] {\n"
"    background-color: #FF0000; /* Piros */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}")
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_22 = QtWidgets.QLabel(parent=self.widget_15)
        self.label_22.setStyleSheet("color: grey;")
        self.label_22.setWordWrap(False)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_10.addWidget(self.label_22)
        self.horizontalLayout_3.addWidget(self.widget_15, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_16 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_16)
        self.label_11.setMinimumSize(QtCore.QSize(40, 40))
        self.label_11.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("/*\n"
" * Függőben lévő (pending) állapot\n"
" * Szürke háttér, halvány szöveg.\n"
" */\n"
"QLabel {\n"
"    background-color: #6c757d; /* Sötétszürke háttér */\n"
"    color: #dee2e6;           /* Világosszürke szöveg */\n"
"    border: 1px solid #adb5bd;/* Szegély a jobb elválasztásért */\n"
"    border-radius: 20px;      /* Kerekítjük a sarkokat (körhöz 50% kell) */\n"
"    padding: 8px;             /* Kisebb belső térköz */\n"
"}\n"
"#label_11[state=\"idle\"] {\n"
"    color: #dee2e6; \n"
"    background-color: #6c757d;\n"
"    font-weight: bold;\n"
"}\n"
"#label_11[state=\"in-progress\"] {\n"
"    background-color: rgb(0,145,245);\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_11[state=\"done\"] {\n"
"    background-color: #008000; /* Zöld */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}\n"
"#label_11[state=\"failed\"] {\n"
"    background-color: #FF0000; /* Piros */\n"
"    color: rgb(255,255,255);\n"
"    font-weight: bold;\n"
"}")
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_21 = QtWidgets.QLabel(parent=self.widget_16)
        self.label_21.setStyleSheet("color: grey;")
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_9.addWidget(self.label_21)
        self.horizontalLayout_3.addWidget(self.widget_16, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_7.setStyleSheet("border: 0px;")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 0px;\n"
"color: rgb(200,200,200);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.tableView = QtWidgets.QTableView(parent=self.widget_7)
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableView.setStyleSheet("background-color: rgb(17, 24, 39);\n"
"border-radius: 5px;\n"
"border: 1px;\n"
"color: rgb(123, 241, 168);")
        self.tableView.setObjectName("tableView")
        self.verticalLayout_5.addWidget(self.tableView)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_4.setStyleSheet("background-color: rgb(31,31,31);\n"
"border: 1px solid rgb(60,60,60);/* Szegély a jobb elválasztásért */\n"
"border-radius: 5px; ")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_10.setStyleSheet("border: 0px;")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 0px;\n"
"color: rgb(200,200,200);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_6.addWidget(self.widget_10)
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_9.setStyleSheet("border: 0px;")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_9)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_17 = QtWidgets.QLabel(parent=self.page_3)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: grey;")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_4)
        self.tableWidget.setStyleSheet("/* Alap táblázat stílus */\n"
"QTableWidget {\n"
"    background-color: #1e1e1e;\n"
"    alternate-background-color: #2e2e2e;\n"
"    gridline-color: #555555;\n"
"    font: 11pt \"Segoe UI\";\n"
"    color: #ffffff;\n"
"    border: 1px solid #3a3a3a;\n"
"}\n"
"\n"
"/* Header stílus */\n"
"QHeaderView::section {\n"
"    background-color: #2d2d30;\n"
"    color: #ffffff;\n"
"    padding: 4px;\n"
"    border: 1px solid #3a3a3a;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Sorok váltakozó szín */\n"
"QTableWidget::item {\n"
"    selection-background-color: #0078d7;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"/* Oszlopok szélei és elválasztó */\n"
"QTableWidget::item:selected {\n"
"    background-color: #0078d7;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* QPushButton a cellában */\n"
"QPushButton {\n"
"    background-color: #3a3a3a;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"    padding: 2px 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #505050;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #686868;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.verticalLayout_6.addWidget(self.widget_9)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Measurement Control Panel"))
        self.label_2.setText(_translate("Dialog", "Start and monitor measurement processes."))
        self.label_3.setText(_translate("Dialog", "Controll Panel"))
        self.label_9.setText(_translate("Dialog", "Port Selection"))
        self.comboBox.setPlaceholderText(_translate("Dialog", "Connect to port first"))
        self.pushButton_2.setText(_translate("Dialog", "Connect"))
        self.pushButton.setText(_translate("Dialog", " Start Measurement"))
        self.label_6.setText(_translate("Dialog", "1"))
        self.label_18.setText(_translate("Dialog", "Connection"))
        self.label_7.setText(_translate("Dialog", "2"))
        self.label_19.setText(_translate("Dialog", "Calibration"))
        self.label_8.setText(_translate("Dialog", "3"))
        self.label_23.setText(_translate("Dialog", "Measurement"))
        self.label_10.setText(_translate("Dialog", "4"))
        self.label_22.setText(_translate("Dialog", "Processing"))
        self.label_11.setText(_translate("Dialog", "5"))
        self.label_21.setText(_translate("Dialog", "Generating files"))
        self.label_4.setText(_translate("Dialog", "Program Logger"))
        self.label_5.setText(_translate("Dialog", "Generated Files"))
        self.label_17.setText(_translate("Dialog", "No generated files."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
