# Form implementation generated from reading ui file 'src/ui/resource.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(1507, 880)
        MainWindow.setMinimumSize(QtCore.QSize(832, 624))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/ui/../../resources/icons/prism.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {background-color: rgb(31, 31, 31);border-top: 1px solid rgba(129,129,129,50);}\n"
"\n"
"QPushButton {\n"
"        border: 0px;\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        background-color: rgb(63, 101, 255);\n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("border: 0px;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(40, 40))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tabWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.tabWidget.setStyleSheet("QTabWidget\n"
"{\n"
"      background: rgb(51, 51, 51);\n"
"}\n"
"QTabWidget::pane {\n"
"    border-top: 1px solid rgba(129,129,129,50);\n"
"    top: 1px;\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"    color: grey;\n"
"    padding: 15 0 15 15;\n"
"    font: 700 10pt \"Consolas\";\n"
"    border: 2px;\n"
"    /*border-top-right-radius: 1px;*/\n"
"    border-left: 1px solid rgba(129, 129, 129, 50);\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"    background-color: rgb(45, 45, 45);\n"
"    border-bottom: 2px solid   rgb(0, 150, 255);\n"
"    /*border-bottom: 1px solid rgb(31,31,31);*/\n"
"    color: white;\n"
"}\n"
"QTabBar::tab:selected:hover{\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"QTabBar::tab:hover { \n"
"      background: rgb(45, 45, 45);\n"
"}\n"
"QTabWidget::tab-bar  {\n"
"left: 54px;\n"
"top: 1px;\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.home = QtWidgets.QWidget()
        self.home.setStyleSheet("background: rgb(20, 20, 20);\n"
"border: 0;")
        self.home.setObjectName("home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.left_navbar = QtWidgets.QWidget(parent=self.home)
        self.left_navbar.setMinimumSize(QtCore.QSize(55, 0))
        self.left_navbar.setMaximumSize(QtCore.QSize(55, 16777215))
        self.left_navbar.setStyleSheet("color:white;\n"
"background-color: rgb(31, 31, 31);\n"
"margin: 0 0 0 0;\n"
"padding: 0 0 0 0;\n"
"border-right:  1px solid rgba(129, 129, 129, 50);\n"
"border-left: 0;")
        self.left_navbar.setObjectName("left_navbar")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.left_navbar)
        self.verticalLayout_11.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_17 = QtWidgets.QWidget(parent=self.left_navbar)
        self.widget_17.setStyleSheet("QWidget {border: 0;margin: 0 0 0 0;}\n"
"\n"
"QPushButton {\n"
"font: 570 10pt \"Consolas\";\n"
"color:     rgb(190, 190, 190);\n"
"margin: 0 0 0 0;\n"
"padding: 5,5,5,5;\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"}\n"
"QPushButton:hover {\n"
"            color: white;\n"
"            background:   rgb(40, 40, 40);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border-left: 3px solid rgb(0, 150, 255);\n"
"        border-radius: 0px;\n"
"        color: white;\n"
"        background:  rgb(40, 40, 40);\n"
"}\n"
"QPushButton:unchecked  {\n"
"        border: 0px;\n"
"        background-color: transparent;\n"
"        color:     rgb(171, 171, 171);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.widget_17)
        self.pushButton_13.setMinimumSize(QtCore.QSize(54, 54))
        self.pushButton_13.setMaximumSize(QtCore.QSize(54, 54))
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_13.setText("")
        icon1 = QtGui.QIcon()
<<<<<<< HEAD
        icon1.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/play-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
=======
        icon1.addPixmap(QtGui.QPixmap("src/ui/../../resources/icons/play-button-arrowhead.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
>>>>>>> d880c57 (Some changes)
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setFlat(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_12.addWidget(self.pushButton_13)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_17)
        self.pushButton_2.setMinimumSize(QtCore.QSize(54, 54))
        self.pushButton_2.setMaximumSize(QtCore.QSize(54, 54))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QToolButton {\n"
"        border: 0px;\n"
"         background: rgb(55, 55, 55);\n"
"\n"
"        font: 700 10pt \"Segoe UI\";\n"
"        }\n"
"QToolButton:hover {\n"
"            background: rgb(75, 75, 75);\n"
"        }\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        icon2 = QtGui.QIcon()
<<<<<<< HEAD
        icon2.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/link.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_12.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout_12.addItem(spacerItem)
        self.verticalLayout_11.addWidget(self.widget_17)
        self.gridLayout_2.addWidget(self.left_navbar, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.home)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
=======
        icon2.addPixmap(QtGui.QPixmap("src/ui/../../resources/icons/link.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setIconSize(QtCore.QSize(15, 15))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout_4.addWidget(self.toolButton_2)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
>>>>>>> d880c57 (Some changes)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("src/ui/../../resources/icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.home, icon3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit_Aplication = QtGui.QAction(parent=MainWindow)
        self.actionExit_Aplication.setObjectName("actionExit_Aplication")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_13.clicked['bool'].connect(MainWindow.HandleMeasureDialog) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.HandleConnectionConfigDialog) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SpectroApp"))
        self.pushButton_13.setToolTip(_translate("MainWindow", "Measure"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "None"))
        self.pushButton_2.setText(_translate("MainWindow", "  Connection status"))
        self.actionExit_Aplication.setText(_translate("MainWindow", "Exit Aplication"))

