# Form implementation generated from reading ui file '.\src\ui\toast_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 60)
        Form.setMinimumSize(QtCore.QSize(350, 0))
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(15, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_4.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ToastIcon = QtWidgets.QLabel(parent=self.widget_4)
        self.ToastIcon.setMinimumSize(QtCore.QSize(40, 40))
        self.ToastIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.ToastIcon.setAutoFillBackground(False)
        self.ToastIcon.setText("")
        self.ToastIcon.setPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/new-moon.png"))
        self.ToastIcon.setScaledContents(True)
        self.ToastIcon.setObjectName("ToastIcon")
        self.gridLayout_4.addWidget(self.ToastIcon, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setStyleSheet("QLabel {\n"
"    color: black;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ToastMessage = QtWidgets.QLabel(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToastMessage.sizePolicy().hasHeightForWidth())
        self.ToastMessage.setSizePolicy(sizePolicy)
        self.ToastMessage.setMinimumSize(QtCore.QSize(0, 0))
        self.ToastMessage.setText("")
        self.ToastMessage.setObjectName("ToastMessage")
        self.gridLayout_2.addWidget(self.ToastMessage, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setMinimumSize(QtCore.QSize(50, 50))
        self.widget_3.setMaximumSize(QtCore.QSize(50, 50))
        self.widget_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.widget_3.setStyleSheet("border: 0px;")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ToastExitButton = QtWidgets.QToolButton(parent=self.widget_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/close-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ToastExitButton.setIcon(icon)
        self.ToastExitButton.setIconSize(QtCore.QSize(20, 20))
        self.ToastExitButton.setAutoRaise(False)
        self.ToastExitButton.setObjectName("ToastExitButton")
        self.gridLayout_3.addWidget(self.ToastExitButton, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.ToastExitButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ToastExitButton.setText(_translate("Form", "..."))
