# Form implementation generated from reading ui file '.\src\ui\widget_creater_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(703, 798)
        Dialog.setStyleSheet("background-color: rgb(20, 20, 20); \n"
"border-radius: 0px;\n"
"    border: 0px;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.page_selector_widget = QtWidgets.QWidget(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_selector_widget.sizePolicy().hasHeightForWidth())
        self.page_selector_widget.setSizePolicy(sizePolicy)
        self.page_selector_widget.setStyleSheet("background: rgb(20,20,20);")
        self.page_selector_widget.setObjectName("page_selector_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_selector_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.page_selector = QtWidgets.QWidget(parent=self.page_selector_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_selector.sizePolicy().hasHeightForWidth())
        self.page_selector.setSizePolicy(sizePolicy)
        self.page_selector.setMinimumSize(QtCore.QSize(200, 0))
        self.page_selector.setStyleSheet("QWidget {background: rgb(31,31,31); \n"
"border-top-left-radius: 2px; \n"
"border-bottom-left-radius: 2px; \n"
"border-right: 1px solid rgba(129, 129, 129,50);}\n"
"\n"
"QPushButton {\n"
"font: 570 10pt \"Consolas\";\n"
"color:     rgb(190, 190, 190);\n"
"margin: 0 0 0 0;\n"
"padding: 5,5,5,5;\n"
"border-radius: 2px;\n"
"border-right: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"            color: white;\n"
"            background:   rgb(40, 40, 40);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border-left: 3px solid rgb(0, 150, 255);\n"
"        border-radius: 0px;\n"
"        color: white;\n"
"        background:  rgb(40, 40, 40);\n"
"}\n"
"QPushButton:unchecked  {\n"
"        border: 0px;\n"
"        background-color: transparent;\n"
"        color:     rgb(171, 171, 171);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.page_selector.setObjectName("page_selector")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_selector)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.custom_widget_button = QtWidgets.QPushButton(parent=self.page_selector)
        self.custom_widget_button.setMinimumSize(QtCore.QSize(60, 35))
        self.custom_widget_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.custom_widget_button.setStyleSheet("")
        self.custom_widget_button.setCheckable(True)
        self.custom_widget_button.setChecked(True)
        self.custom_widget_button.setObjectName("custom_widget_button")
        self.WidgetTypeGroup = QtWidgets.QButtonGroup(Dialog)
        self.WidgetTypeGroup.setObjectName("WidgetTypeGroup")
        self.WidgetTypeGroup.addButton(self.custom_widget_button)
        self.verticalLayout.addWidget(self.custom_widget_button)
        self.custom_widget_button_2 = QtWidgets.QPushButton(parent=self.page_selector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custom_widget_button_2.sizePolicy().hasHeightForWidth())
        self.custom_widget_button_2.setSizePolicy(sizePolicy)
        self.custom_widget_button_2.setMinimumSize(QtCore.QSize(60, 35))
        self.custom_widget_button_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.custom_widget_button_2.setCheckable(True)
        self.custom_widget_button_2.setObjectName("custom_widget_button_2")
        self.WidgetTypeGroup.addButton(self.custom_widget_button_2)
        self.verticalLayout.addWidget(self.custom_widget_button_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page_selector)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.page_selector)
        self.page_widget = QtWidgets.QWidget(parent=self.page_selector_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_widget.sizePolicy().hasHeightForWidth())
        self.page_widget.setSizePolicy(sizePolicy)
        self.page_widget.setStyleSheet("    border: 0px;")
        self.page_widget.setObjectName("page_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_widget)
        self.verticalLayout_2.setContentsMargins(0, 2, 0, 2)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.page_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setStyleSheet("border: 0px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setMinimumSize(QtCore.QSize(0, 0))
        self.page.setStyleSheet("border: 0px;")
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spectral_preview_widget = QtWidgets.QWidget(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectral_preview_widget.sizePolicy().hasHeightForWidth())
        self.spectral_preview_widget.setSizePolicy(sizePolicy)
        self.spectral_preview_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.spectral_preview_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spectral_preview_widget.setStyleSheet("background-color:rgb(21,21,21);")
        self.spectral_preview_widget.setObjectName("spectral_preview_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.spectral_preview_widget)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout.addWidget(self.spectral_preview_widget, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setStyleSheet("QTabWidget\n"
"{\n"
"    border: 0px;\n"
"      background: rgb(31,31,31);\n"
"}\n"
"QTabWidget::pane {\n"
"    top: 5px;\n"
"    border-top: 3px solid rgb(0, 0, 0);\n"
"    border-left: 3px solid rgb(0, 0, 0);\n"
"    border-right: 3px solid rgb(0, 0, 0);\n"
"    border-bottom: 3px solid rgb(0, 0, 0);\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"    color: grey;\n"
"    padding: 10 15 10 15;\n"
"    font: 700 10pt \"Consolas\";\n"
"      background: rgb(31,31,31);\n"
"    /*border-top-right-radius: 1px;\n"
"    border-top-left-radius: 1px;*/\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"    background-color: rgb(45, 45, 45);\n"
"    border-bottom: 2px solid   rgb(0, 150, 255);\n"
"    /*border-bottom: 1px solid rgb(31,31,31);*/\n"
"    color: white;\n"
"}\n"
"QTabBar::tab:selected:hover{\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"QTabBar::tab:hover { \n"
"      background: rgb(45, 45, 45);\n"
"}\n"
"QTabWidget::tab-bar  {\n"
"left: 5px;\n"
"top: 0px;\n"
"border: 2px solid blue;\n"
"}b ")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"  margin-top: 1.4em;\n"
"  margin-bottom: 0.5;\n"
"  font: 700 12pt \"Consolas\";\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background: transparent;\n"
"  color: white;\n"
"  padding-top: -30px;\n"
"   padding-left: -18px;\n"
"  margin: 0 15 15 15;\n"
"}\n"
"QLabel {\n"
"    color: grey;\n"
"    font: 550 11pt \"Consolas\";\n"
"}\n"
"QSpinBox {\n"
"        font: 600 10pt \"Segoe UI\";\n"
"         background-color:  rgb(41,41,41);\n"
"        color: grey;\n"
"        border-radius: 2px;\n"
"}\n"
"QComboBox {\n"
"        font: 700 10pt \"Segoe UI\";\n"
"         background-color:  rgb(41,41,41);\n"
"        color: grey;\n"
"        border-radius: 2px;\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.groupBox)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 285, 120))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_5 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_3)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_9.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_7.setMinimumSize(QtCore.QSize(0, 40))
        self.label_7.setMaximumSize(QtCore.QSize(100, 40))
        self.label_7.setStyleSheet("border: 1px solid rgba(129, 129, 129, 50); color: grey")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.comboBox_4 = QtWidgets.QComboBox(parent=self.widget_5)
        self.comboBox_4.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_4.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_4)
        self.gridLayout_7.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_3)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(100, 40))
        self.label.setMaximumSize(QtCore.QSize(100, 38))
        self.label.setStyleSheet("border: 1px solid rgba(129, 129, 129, 50); color: grey")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(parent=self.widget_2)
        self.spinBox.setMinimumSize(QtCore.QSize(100, 40))
        self.spinBox.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.spinBox.setMaximum(9999)
        self.spinBox.setProperty("value", 660)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_2)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.gridLayout_7.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_3)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_2.setMinimumSize(QtCore.QSize(100, 40))
        self.label_2.setMaximumSize(QtCore.QSize(100, 35))
        self.label_2.setStyleSheet("border: 1px solid rgba(129, 129, 129, 50); color: grey")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(parent=self.widget_3)
        self.spinBox_2.setMinimumSize(QtCore.QSize(100, 40))
        self.spinBox_2.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_2.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.spinBox_2.setMaximum(9999)
        self.spinBox_2.setProperty("value", 400)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_4.addWidget(self.spinBox_2)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.widget_3)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_2.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.gridLayout_7.addWidget(self.widget_3, 2, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.scrollArea_3)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 2)
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"  border-radius: 2px;\n"
"  margin-top: 1.4em;\n"
"  margin-bottom: 1;\n"
"  font: 700 12pt \"Consolas\";\n"
"}\n"
"QLineEdit {\n"
"    font: 600 10pt \"Segoe UI\";\n"
"    background-color:  rgb(41,41,41);\n"
"   color: white;\n"
"    border-radius: 2px;\n"
"}\n"
"QPushButton {\n"
"    background: rgb(0, 150, 255);\n"
"    color: rgba(255,255,255, 0.85);\n"
"    border-radius: 2px;\n"
"    font: 600 10pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(51, 180, 255);\n"
"}\n"
"QGroupBox::title {\n"
"  background: transparent;\n"
"  color: white;\n"
"  padding-top: -30px;\n"
"   padding-left: -18px;\n"
"  margin: 0 15 15 15;\n"
"}\n"
"QLabel {\n"
"    color: grey;\n"
"    font: 550 11pt \"Consolas\";\n"
"}\n"
"QSpinBox {\n"
"        font: 600 10pt \"Segoe UI\";\n"
"         background-color:  rgb(41,41,41);\n"
"        color: grey;\n"
"        border-radius: 2px;\n"
"        border: 0px;\n"
"}\n"
"QComboBox {\n"
"        font: 700 10pt \"Segoe UI\";\n"
"         background-color:  rgb(41,41,41);\n"
"        color: grey;\n"
"        border-radius: 2px;\n"
"        border: 0px;\n"
"}")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(0, 1, 0, 1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(parent=self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setStyleSheet("\n"
"QWidget {\n"
"\n"
"    border-top: 1px solid rgba(129, 129, 129, 50);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(149, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(149, 999))
        self.pushButton.setStyleSheet("border: 0px; border-radius: 0px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_4.setStyleSheet("background-color:  rgb(41,41,41);\n"
"border:0px;\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_10.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.horizontalLayout_5.addWidget(self.widget_4)
        self.verticalLayout_4.addWidget(self.widget)
        self.widget_9 = QtWidgets.QWidget(parent=self.groupBox_2)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_9.setStyleSheet("")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_4.setStyleSheet("border: 1px solid rgba(129, 129, 129, 50); color: grey")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.spinBox_4 = QtWidgets.QSpinBox(parent=self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_4.sizePolicy().hasHeightForWidth())
        self.spinBox_4.setSizePolicy(sizePolicy)
        self.spinBox_4.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBox_4.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.spinBox_4.setMinimum(380)
        self.spinBox_4.setMaximum(719)
        self.spinBox_4.setProperty("value", 380)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_7.addWidget(self.spinBox_4)
        self.comboBox_6 = QtWidgets.QComboBox(parent=self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_6.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_6)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(parent=self.groupBox_2)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_10.setStyleSheet("")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_5.setStyleSheet("border: 1px solid rgba(129, 129, 129, 50); color: grey")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.spinBox_5 = QtWidgets.QSpinBox(parent=self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_5.sizePolicy().hasHeightForWidth())
        self.spinBox_5.setSizePolicy(sizePolicy)
        self.spinBox_5.setMinimumSize(QtCore.QSize(100, 35))
        self.spinBox_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBox_5.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.spinBox_5.setMinimum(401)
        self.spinBox_5.setMaximum(780)
        self.spinBox_5.setProperty("value", 780)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_8.addWidget(self.spinBox_5)
        self.comboBox_7 = QtWidgets.QComboBox(parent=self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_7.sizePolicy().hasHeightForWidth())
        self.comboBox_7.setSizePolicy(sizePolicy)
        self.comboBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_7.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_7)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.widget_19 = QtWidgets.QWidget(parent=self.groupBox_2)
        self.widget_19.setStyleSheet("\n"
"QWidget {\n"
"\n"
"}\n"
"")
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_19.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.widget_20 = QtWidgets.QWidget(parent=self.widget_19)
        self.widget_20.setStyleSheet("QWidget {border: 1px solid rgba(129, 129, 129, 50); color: grey}")
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_19.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_19.setSpacing(2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_37 = QtWidgets.QLabel(parent=self.widget_20)
        self.label_37.setMinimumSize(QtCore.QSize(150, 50))
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_37.setStyleSheet("border: 0px; color: white;")
        self.label_37.setObjectName("label_37")
        self.verticalLayout_19.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(parent=self.widget_20)
        self.label_38.setMinimumSize(QtCore.QSize(0, 18))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_38.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_38.setStyleSheet("border:0;")
        self.label_38.setScaledContents(False)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_19.addWidget(self.label_38)
        self.horizontalLayout_19.addWidget(self.widget_20)
        self.checkBox_7 = QtWidgets.QCheckBox(parent=self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_7.sizePolicy().hasHeightForWidth())
        self.checkBox_7.setSizePolicy(sizePolicy)
        self.checkBox_7.setMinimumSize(QtCore.QSize(50, 0))
        self.checkBox_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.checkBox_7.setStyleSheet("QCheckBox {\n"
"    border-top: 1px solid rgba(129, 129, 129, 50);\n"
"    border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(./resources/icons/toggle-button-on.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(./resources/icons/toggle-button-off.png);\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}")
        self.checkBox_7.setText("")
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_19.addWidget(self.checkBox_7)
        self.verticalLayout_4.addWidget(self.widget_19)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.groupBox_2)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 429, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_11 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_2)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_11.setStyleSheet("\n"
"QWidget {\n"
"\n"
"}\n"
"")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_11.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_6.setStyleSheet("border: 1px solid rgba(129, 129, 129, 50); color: grey")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.spinBox_6 = QtWidgets.QSpinBox(parent=self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_6.sizePolicy().hasHeightForWidth())
        self.spinBox_6.setSizePolicy(sizePolicy)
        self.spinBox_6.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBox_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBox_6.setSizeIncrement(QtCore.QSize(0, 0))
        self.spinBox_6.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.spinBox_6.setMaximum(9999)
        self.spinBox_6.setProperty("value", 300)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_11.addWidget(self.spinBox_6)
        self.comboBox_8 = QtWidgets.QComboBox(parent=self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        self.comboBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_8.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_8)
        self.gridLayout_6.addWidget(self.widget_11, 3, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tabWidget_2 = QtWidgets.QTabWidget(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_2.setStyleSheet("QTabWidget\n"
"{\n"
"    border: 0px;\n"
"      background: rgb(31,31,31);\n"
"}\n"
"QTabWidget::pane {\n"
"    top: 5px;\n"
"    border-top: 3px solid rgb(0, 0, 0);\n"
"    border-left: 3px solid rgb(0, 0, 0);\n"
"    border-right: 3px solid rgb(0, 0, 0);\n"
"    border-bottom: 3px solid rgb(0, 0, 0);\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"    color: grey;\n"
"    padding: 10 15 10 15;\n"
"    font: 700 10pt \"Consolas\";\n"
"      background: rgb(31,31,31);\n"
"    /*border-top-right-radius: 1px;\n"
"    border-top-left-radius: 1px;*/\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"    background-color: rgb(45, 45, 45);\n"
"    border-bottom: 2px solid   rgb(0, 150, 255);\n"
"    /*border-bottom: 1px solid rgb(31,31,31);*/\n"
"    color: white;\n"
"}\n"
"QTabBar::tab:selected:hover{\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"QTabBar::tab:hover { \n"
"      background: rgb(45, 45, 45);\n"
"}\n"
"QTabWidget::tab-bar  {\n"
"left: 5px;\n"
"top: 0px;\n"
"border: 2px solid blue;\n"
"}b ")
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setMaximumSize(QtCore.QSize(16777215, 300))
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.tab_7)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_7.setStyleSheet("QGroupBox {\n"
"  border-radius: 2px;\n"
"  margin-top: 1.4em;\n"
"  margin-bottom: 0.5;\n"
"  font: 700 12pt \"Consolas\";\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background: transparent;\n"
"  color: white;\n"
"  padding-top: -30px;\n"
"   padding-left: -18px;\n"
"  margin: 0 15 15 15;\n"
"}\n"
"QLabel {\n"
"    color: grey;\n"
"    font: 550 11pt \"Consolas\";\n"
"}\n"
"QSpinBox {\n"
"        font: 600 10pt \"Segoe UI\";\n"
"         background-color:  rgb(41,41,41);\n"
"        color: grey;\n"
"        border-radius: 2px;\n"
"}\n"
"QComboBox {\n"
"        font: 700 10pt \"Segoe UI\";\n"
"         background-color:  rgb(41,41,41);\n"
"        color: grey;\n"
"        border-radius: 2px;\n"
"}")
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_9.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_26 = QtWidgets.QWidget(parent=self.groupBox_7)
        self.widget_26.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_26.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.widget_26)
        self.horizontalLayout_28.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_28.setSpacing(5)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_22 = QtWidgets.QLabel(parent=self.widget_26)
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        self.label_22.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_28.addWidget(self.label_22)
        self.comboBox_19 = QtWidgets.QComboBox(parent=self.widget_26)
        self.comboBox_19.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.setItemText(0, "")
        self.comboBox_19.addItem("")
        self.horizontalLayout_28.addWidget(self.comboBox_19)
        self.verticalLayout_9.addWidget(self.widget_26)
        self.widget_27 = QtWidgets.QWidget(parent=self.groupBox_7)
        self.widget_27.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_27.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_27.setStyleSheet("")
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_29.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_29.setSpacing(5)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_23 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_23.setMinimumSize(QtCore.QSize(100, 0))
        self.label_23.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_29.addWidget(self.label_23)
        self.spinBox_16 = QtWidgets.QSpinBox(parent=self.widget_27)
        self.spinBox_16.setMinimumSize(QtCore.QSize(100, 35))
        self.spinBox_16.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBox_16.setMaximum(9999)
        self.spinBox_16.setProperty("value", 400)
        self.spinBox_16.setObjectName("spinBox_16")
        self.horizontalLayout_29.addWidget(self.spinBox_16)
        self.comboBox_20 = QtWidgets.QComboBox(parent=self.widget_27)
        self.comboBox_20.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBox_20.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.horizontalLayout_29.addWidget(self.comboBox_20)
        self.verticalLayout_9.addWidget(self.widget_27)
        self.widget_28 = QtWidgets.QWidget(parent=self.groupBox_7)
        self.widget_28.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_28.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_28.setObjectName("widget_28")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.widget_28)
        self.horizontalLayout_30.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_30.setSpacing(5)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_24 = QtWidgets.QLabel(parent=self.widget_28)
        self.label_24.setMinimumSize(QtCore.QSize(100, 0))
        self.label_24.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_30.addWidget(self.label_24)
        self.spinBox_17 = QtWidgets.QSpinBox(parent=self.widget_28)
        self.spinBox_17.setMinimumSize(QtCore.QSize(100, 35))
        self.spinBox_17.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBox_17.setMaximum(9999)
        self.spinBox_17.setProperty("value", 400)
        self.spinBox_17.setObjectName("spinBox_17")
        self.horizontalLayout_30.addWidget(self.spinBox_17)
        self.comboBox_21 = QtWidgets.QComboBox(parent=self.widget_28)
        self.comboBox_21.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBox_21.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.horizontalLayout_30.addWidget(self.comboBox_21)
        self.verticalLayout_9.addWidget(self.widget_28)
        self.gridLayout_11.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 2)
        self.gridLayout_12.setSpacing(1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 478, 548))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_8 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_8.setStyleSheet("QGroupBox {\n"
"  border-radius: 2px;\n"
"  margin-top: 1.4em;\n"
"  margin-bottom: 1;\n"
"  font: 700 12pt \"Consolas\";\n"
"}\n"
"QLineEdit {\n"
"    font: 600 10pt \"Segoe UI\";\n"
"    background-color:  rgb(41,41,41);\n"
"   color: white;\n"
"    border-radius: 2px;\n"
"}\n"
"QPushButton {\n"
"    background: rgb(0, 150, 255);\n"
"    color: rgba(255,255,255, 0.85);\n"
"    border-radius: 2px;\n"
"    font: 600 10pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(51, 180, 255);\n"
"}\n"
"QGroupBox::title {\n"
"  background: transparent;\n"
"  color: white;\n"
"  padding-top: -30px;\n"
"   padding-left: -18px;\n"
"  margin: 0 15 15 15;\n"
"}\n"
"QLabel {\n"
"    color: grey;\n"
"    font: 550 11pt \"Consolas\";\n"
"}\n"
"QSpinBox {\n"
"        font: 600 10pt \"Segoe UI\";\n"
"         background-color:  rgb(41,41,41);\n"
"        color: grey;\n"
"        border-radius: 2px;\n"
"        border: 0px;\n"
"}\n"
"QComboBox {\n"
"        font: 700 10pt \"Segoe UI\";\n"
"         background-color:  rgb(41,41,41);\n"
"        color: grey;\n"
"        border-radius: 2px;\n"
"        border: 0px;\n"
"}")
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_10.setContentsMargins(0, 1, 0, 1)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_29 = QtWidgets.QWidget(parent=self.groupBox_8)
        self.widget_29.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_29.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_29.setStyleSheet("\n"
"QWidget {\n"
"\n"
"    border-top: 1px solid rgba(129, 129, 129, 50);\n"
"}\n"
"")
        self.widget_29.setObjectName("widget_29")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.widget_29)
        self.horizontalLayout_31.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(149, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(149, 999))
        self.pushButton_4.setStyleSheet("border: 0px; border-radius: 0px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_31.addWidget(self.pushButton_4)
        self.widget_30 = QtWidgets.QWidget(parent=self.widget_29)
        self.widget_30.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_30.setStyleSheet("background-color:  rgb(41,41,41);\n"
"border:0px;\n"
"")
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_32.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_25 = QtWidgets.QLabel(parent=self.widget_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_32.addWidget(self.label_25)
        self.horizontalLayout_31.addWidget(self.widget_30)
        self.verticalLayout_10.addWidget(self.widget_29)
        self.widget_8 = QtWidgets.QWidget(parent=self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(150, 50))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_12 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_12.setStyleSheet("QWidget {border: 1px solid rgba(129, 129, 129, 50); color: grey}")
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_12)
        self.label_9.setMinimumSize(QtCore.QSize(150, 50))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setStyleSheet("border: 0px; color: white;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.widget_12)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 36))
        self.label_10.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_10.setStyleSheet("border:0;")
        self.label_10.setScaledContents(False)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.horizontalLayout_13.addWidget(self.widget_12)
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.widget_8)
        self.checkBox_5.setMinimumSize(QtCore.QSize(50, 50))
        self.checkBox_5.setMaximumSize(QtCore.QSize(50, 999))
        self.checkBox_5.setStyleSheet("QCheckBox {\n"
"    border-top: 1px solid rgba(129, 129, 129, 50);\n"
"    border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(./resources/icons/toggle-button-on.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(./resources/icons/toggle-button-off.png);\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}")
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_13.addWidget(self.checkBox_5)
        self.verticalLayout_10.addWidget(self.widget_8)
        self.widget_7 = QtWidgets.QWidget(parent=self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(150, 50))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_7.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widget_13 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_13.setStyleSheet("QWidget {border: 1px solid rgba(129, 129, 129, 50); color: grey}")
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_19 = QtWidgets.QLabel(parent=self.widget_13)
        self.label_19.setMinimumSize(QtCore.QSize(150, 50))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_19.setStyleSheet("border: 0px; color: white;")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(parent=self.widget_13)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_20.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_20.setStyleSheet("border:0;")
        self.label_20.setScaledContents(False)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_12.addWidget(self.label_20)
        self.horizontalLayout_12.addWidget(self.widget_13)
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setMinimumSize(QtCore.QSize(50, 50))
        self.checkBox_4.setMaximumSize(QtCore.QSize(50, 999))
        self.checkBox_4.setStyleSheet("QCheckBox {\n"
"    border-top: 1px solid rgba(129, 129, 129, 50);\n"
"    border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(./resources/icons/toggle-button-on.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(./resources/icons/toggle-button-off.png);\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_12.addWidget(self.checkBox_4)
        self.verticalLayout_10.addWidget(self.widget_7)
        self.widget_31 = QtWidgets.QWidget(parent=self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_31.sizePolicy().hasHeightForWidth())
        self.widget_31.setSizePolicy(sizePolicy)
        self.widget_31.setMinimumSize(QtCore.QSize(150, 50))
        self.widget_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_31.setStyleSheet("")
        self.widget_31.setObjectName("widget_31")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_31)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_14 = QtWidgets.QWidget(parent=self.widget_31)
        self.widget_14.setStyleSheet("QWidget {border: 1px solid rgba(129, 129, 129, 50); color: grey}")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_14.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_14.setSpacing(2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_14)
        self.label_29.setMinimumSize(QtCore.QSize(150, 50))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_29.setStyleSheet("border: 0px; color: white;")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_14.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(parent=self.widget_14)
        self.label_30.setMinimumSize(QtCore.QSize(0, 18))
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_30.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_30.setStyleSheet("border:0;")
        self.label_30.setScaledContents(False)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_14.addWidget(self.label_30)
        self.horizontalLayout_15.addWidget(self.widget_14)
        self.checkBox = QtWidgets.QCheckBox(parent=self.widget_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMinimumSize(QtCore.QSize(50, 0))
        self.checkBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    border-top: 1px solid rgba(129, 129, 129, 50);\n"
"    border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(./resources/icons/toggle-button-on.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(./resources/icons/toggle-button-off.png);\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_15.addWidget(self.checkBox)
        self.verticalLayout_10.addWidget(self.widget_31)
        self.widget_32 = QtWidgets.QWidget(parent=self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_32.sizePolicy().hasHeightForWidth())
        self.widget_32.setSizePolicy(sizePolicy)
        self.widget_32.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_32.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_32.setStyleSheet("")
        self.widget_32.setObjectName("widget_32")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_32)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widget_16 = QtWidgets.QWidget(parent=self.widget_32)
        self.widget_16.setStyleSheet("QWidget {border: 1px solid rgba(129, 129, 129, 50); color: grey}")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_31 = QtWidgets.QLabel(parent=self.widget_16)
        self.label_31.setMinimumSize(QtCore.QSize(150, 50))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_31.setStyleSheet("border: 0px; color: white;")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_15.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(parent=self.widget_16)
        self.label_32.setMinimumSize(QtCore.QSize(0, 18))
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_32.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_32.setStyleSheet("border:0;")
        self.label_32.setScaledContents(False)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_15.addWidget(self.label_32)
        self.horizontalLayout_16.addWidget(self.widget_16)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.widget_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setMinimumSize(QtCore.QSize(50, 0))
        self.checkBox_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"    border-top: 1px solid rgba(129, 129, 129, 50);\n"
"    border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(./resources/icons/toggle-button-on.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(./resources/icons/toggle-button-off.png);\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}")
        self.checkBox_2.setText("")
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_16.addWidget(self.checkBox_2)
        self.verticalLayout_10.addWidget(self.widget_32)
        self.widget_33 = QtWidgets.QWidget(parent=self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_33.sizePolicy().hasHeightForWidth())
        self.widget_33.setSizePolicy(sizePolicy)
        self.widget_33.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_33.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_33.setStyleSheet("\n"
"QWidget {\n"
"    border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"}\n"
"")
        self.widget_33.setObjectName("widget_33")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_33)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_17 = QtWidgets.QWidget(parent=self.widget_33)
        self.widget_17.setStyleSheet("QWidget {border: 1px solid rgba(129, 129, 129, 50); color: grey}")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_16.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_16.setSpacing(2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_33 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_33.setMinimumSize(QtCore.QSize(150, 50))
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_33.setStyleSheet("border: 0px; color: white;")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_16.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_34.setMinimumSize(QtCore.QSize(0, 18))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_34.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_34.setStyleSheet("border:0;")
        self.label_34.setScaledContents(False)
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_16.addWidget(self.label_34)
        self.horizontalLayout_17.addWidget(self.widget_17)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.widget_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setMinimumSize(QtCore.QSize(50, 0))
        self.checkBox_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.checkBox_3.setStyleSheet("QCheckBox {\n"
"    border-top: 1px solid rgba(129, 129, 129, 50);\n"
"    border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(./resources/icons/toggle-button-on.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(./resources/icons/toggle-button-off.png);\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}")
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_17.addWidget(self.checkBox_3)
        self.verticalLayout_10.addWidget(self.widget_33)
        self.widget_18 = QtWidgets.QWidget(parent=self.groupBox_8)
        self.widget_18.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_18.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_18)
        self.label_8.setMinimumSize(QtCore.QSize(150, 0))
        self.label_8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_8.setStyleSheet("border: 1px solid rgba(129, 129, 129, 50); color: grey")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_18.addWidget(self.label_8)
        self.spinBox_7 = QtWidgets.QSpinBox(parent=self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_7.sizePolicy().hasHeightForWidth())
        self.spinBox_7.setSizePolicy(sizePolicy)
        self.spinBox_7.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBox_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spinBox_7.setSizeIncrement(QtCore.QSize(0, 0))
        self.spinBox_7.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.spinBox_7.setMaximum(9999)
        self.spinBox_7.setProperty("value", 300)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_18.addWidget(self.spinBox_7)
        self.comboBox_9 = QtWidgets.QComboBox(parent=self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_9.setStyleSheet("border-top: 1px solid rgba(129, 129, 129, 50);\n"
"border-bottom: 1px solid rgba(129, 129, 129, 50);\n"
"border-radius: 0px;")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_9)
        self.verticalLayout_10.addWidget(self.widget_18)
        self.gridLayout_3.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_12.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.spectral_preview_widget_2 = QtWidgets.QWidget(parent=self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectral_preview_widget_2.sizePolicy().hasHeightForWidth())
        self.spectral_preview_widget_2.setSizePolicy(sizePolicy)
        self.spectral_preview_widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.spectral_preview_widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spectral_preview_widget_2.setStyleSheet("background-color:rgb(21,21,21);")
        self.spectral_preview_widget_2.setObjectName("spectral_preview_widget_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.spectral_preview_widget_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12.addWidget(self.spectral_preview_widget_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.gridLayout_14.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget_3 = QtWidgets.QTabWidget(parent=self.page_3)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.gridLayout_8.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.widget_6 = QtWidgets.QWidget(parent=self.page_widget)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_6.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 12pt;\n"
"          background-color: rgb(45, 45, 45);\n"
"        color: grey;\n"
"        padding: 1 1 1 1;\n"
"        font: 700 11pt \"Consolas\";\n"
"border-radius: 2px;\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        background-color : rgb(0, 150, 255);;\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.CreateWidgetPushButton = QtWidgets.QPushButton(parent=self.widget_6)
        self.CreateWidgetPushButton.setMinimumSize(QtCore.QSize(100, 35))
        self.CreateWidgetPushButton.setMaximumSize(QtCore.QSize(100, 35))
        self.CreateWidgetPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CreateWidgetPushButton.setStyleSheet("QPushButton {\n"
"    background: rgb(0, 150, 255);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(51, 180, 255);\n"
"}")
        self.CreateWidgetPushButton.setObjectName("CreateWidgetPushButton")
        self.horizontalLayout_6.addWidget(self.CreateWidgetPushButton)
        self.CancelCreateWidget = QtWidgets.QPushButton(parent=self.widget_6)
        self.CancelCreateWidget.setMinimumSize(QtCore.QSize(100, 35))
        self.CancelCreateWidget.setMaximumSize(QtCore.QSize(100, 35))
        self.CancelCreateWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CancelCreateWidget.setStyleSheet("QPushButton {\n"
"            font: 650 11pt \"Consolas\";\n"
"}")
        self.CancelCreateWidget.setObjectName("CancelCreateWidget")
        self.horizontalLayout_6.addWidget(self.CancelCreateWidget)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.horizontalLayout_2.addWidget(self.page_widget)
        self.horizontalLayout.addWidget(self.page_selector_widget)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.CreateWidgetPushButton.clicked.connect(Dialog.onCreateWidget) # type: ignore
        self.CancelCreateWidget.clicked.connect(Dialog.onCancel) # type: ignore
        self.custom_widget_button.clicked.connect(Dialog.onCustomWidgetClicked) # type: ignore
        self.custom_widget_button_2.clicked.connect(Dialog.onCustomWidget2Clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.custom_widget_button.setText(_translate("Dialog", "Spectrum Colors"))
        self.custom_widget_button_2.setText(_translate("Dialog", "Spectrum Locus"))
        self.pushButton_2.setText(_translate("Dialog", "Daylight Locus"))
        self.groupBox.setTitle(_translate("Dialog", "Widget Size"))
        self.label_7.setText(_translate("Dialog", "Predifined"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "128x128 (128ppi)"))
        self.label.setText(_translate("Dialog", "Width"))
        self.comboBox.setItemText(0, _translate("Dialog", "Pixels (px)"))
        self.comboBox.setItemText(1, _translate("Dialog", "Points (pt)"))
        self.label_2.setText(_translate("Dialog", "Height"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Pixels (px)"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Points (pt)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Dimensions"))
        self.groupBox_2.setTitle(_translate("Dialog", "Widget Properties"))
        self.pushButton.setText(_translate("Dialog", "Choose file"))
        self.label_3.setText(_translate("Dialog", "No measurement file choosen"))
        self.label_4.setText(_translate("Dialog", "Min Wavelength "))
        self.comboBox_6.setItemText(0, _translate("Dialog", "Nanometres (nm)"))
        self.label_5.setText(_translate("Dialog", "Max Wavelength"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "Nanometres (nm)"))
        self.label_37.setText(_translate("Dialog", "Show Grid"))
        self.label_38.setText(_translate("Dialog", "Show grid (True) or not (False)"))
        self.label_6.setText(_translate("Dialog", "Resolution"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "Pixels (px) per Inch"))
        self.comboBox_8.setItemText(1, _translate("Dialog", "Pixels (px) per Centimeter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Content"))
        self.groupBox_7.setTitle(_translate("Dialog", "Widget Size"))
        self.label_22.setText(_translate("Dialog", "Predifined"))
        self.comboBox_19.setItemText(1, _translate("Dialog", "128x128 (128ppi)"))
        self.label_23.setText(_translate("Dialog", "Width"))
        self.comboBox_20.setItemText(0, _translate("Dialog", "Pixels (px)"))
        self.comboBox_20.setItemText(1, _translate("Dialog", "Points (pt)"))
        self.label_24.setText(_translate("Dialog", "Height"))
        self.comboBox_21.setItemText(0, _translate("Dialog", "Pixels (px)"))
        self.comboBox_21.setItemText(1, _translate("Dialog", "Points (pt)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Dialog", "Dimensions"))
        self.groupBox_8.setTitle(_translate("Dialog", "Widget Properties"))
        self.pushButton_4.setText(_translate("Dialog", "Choose file"))
        self.label_25.setText(_translate("Dialog", "No measurement file choosen"))
        self.label_9.setText(_translate("Dialog", "cct text labels "))
        self.label_10.setText(_translate("Dialog", "Add cct text labels at various points along the blackbody locus."))
        self.checkBox_5.setText(_translate("Dialog", "CheckBox"))
        self.label_19.setText(_translate("Dialog", "EEW"))
        self.label_20.setText(_translate("Dialog", "Plots Equi-Energy-White chromaticity as well. "))
        self.checkBox_4.setText(_translate("Dialog", "CheckBox"))
        self.label_29.setText(_translate("Dialog", "DL"))
        self.label_30.setText(_translate("Dialog", "plots Daylight Locus as well."))
        self.label_31.setText(_translate("Dialog", "BBL"))
        self.label_32.setText(_translate("Dialog", "plots BlackBody Locus as well. "))
        self.label_33.setText(_translate("Dialog", "D65"))
        self.label_34.setText(_translate("Dialog", "plots D65 chromaticity as well. "))
        self.label_8.setText(_translate("Dialog", "Resolution"))
        self.comboBox_9.setItemText(0, _translate("Dialog", "Pixels (px) per Inch"))
        self.comboBox_9.setItemText(1, _translate("Dialog", "Pixels (px) per Centimeter"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("Dialog", "Content"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("Dialog", "Tab 1"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("Dialog", "Tab 2"))
        self.CreateWidgetPushButton.setText(_translate("Dialog", "Create"))
        self.CancelCreateWidget.setText(_translate("Dialog", "Cancel"))
