# Form implementation generated from reading ui file '.\src\ui\workspaceDesignFomr.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WorkspaceDesignForm(object):
    def setupUi(self, WorkspaceDesignForm):
        WorkspaceDesignForm.setObjectName("WorkspaceDesignForm")
        WorkspaceDesignForm.resize(1307, 800)
        WorkspaceDesignForm.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        WorkspaceDesignForm.setStyleSheet("margin: 0 0 0 0;")
        self.gridLayout = QtWidgets.QGridLayout(WorkspaceDesignForm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scene_widget = QtWidgets.QWidget(parent=WorkspaceDesignForm)
        self.scene_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scene_widget.sizePolicy().hasHeightForWidth())
        self.scene_widget.setSizePolicy(sizePolicy)
        self.scene_widget.setMinimumSize(QtCore.QSize(495, 800))
        self.scene_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scene_widget.setAutoFillBackground(False)
        self.scene_widget.setStyleSheet("background-color: rgb(20, 20, 20); \n"
"/*border-top: 1px solid rgba(129, 129, 129, 50);*/\n"
"border-bottom: 0;")
        self.scene_widget.setObjectName("scene_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scene_widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.workspace_container = QtWidgets.QWidget(parent=self.scene_widget)
        self.workspace_container.setMinimumSize(QtCore.QSize(0, 0))
        self.workspace_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.workspace_container.setStyleSheet("border: 0px;")
        self.workspace_container.setObjectName("workspace_container")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.workspace_container)
        self.gridLayout_5.setContentsMargins(5, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_8 = QtWidgets.QWidget(parent=self.workspace_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_8.setMaximumSize(QtCore.QSize(55, 205))
        self.widget_8.setStyleSheet("QWidget {\n"
"background-color: rgb(35, 35, 35);\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"        border: 0px;\n"
"        font: 12pt;\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        background-color : rgb(0, 150, 255);;\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SelectButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.SelectButton.setMinimumSize(QtCore.QSize(40, 40))
        self.SelectButton.setMaximumSize(QtCore.QSize(40, 40))
        self.SelectButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SelectButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/cursor.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.SelectButton.setIcon(icon)
        self.SelectButton.setCheckable(True)
        self.SelectButton.setChecked(False)
        self.SelectButton.setAutoExclusive(True)
        self.SelectButton.setObjectName("SelectButton")
        self.WorkspaceButtonGroup = QtWidgets.QButtonGroup(WorkspaceDesignForm)
        self.WorkspaceButtonGroup.setObjectName("WorkspaceButtonGroup")
        self.WorkspaceButtonGroup.addButton(self.SelectButton)
        self.verticalLayout_7.addWidget(self.SelectButton)
        self.line = QtWidgets.QFrame(parent=self.widget_8)
        self.line.setStyleSheet("background: rgba(129, 129, 129, 50);")
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.DeleteWidgetButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.DeleteWidgetButton.setMinimumSize(QtCore.QSize(40, 40))
        self.DeleteWidgetButton.setMaximumSize(QtCore.QSize(40, 40))
        self.DeleteWidgetButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.DeleteWidgetButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.DeleteWidgetButton.setIcon(icon1)
        self.DeleteWidgetButton.setIconSize(QtCore.QSize(15, 15))
        self.DeleteWidgetButton.setCheckable(True)
        self.DeleteWidgetButton.setChecked(False)
        self.DeleteWidgetButton.setObjectName("DeleteWidgetButton")
        self.WorkspaceButtonGroup.addButton(self.DeleteWidgetButton)
        self.verticalLayout_7.addWidget(self.DeleteWidgetButton)
        self.line_2 = QtWidgets.QFrame(parent=self.widget_8)
        self.line_2.setStyleSheet("background: rgba(129, 129, 129, 50);")
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.DragOnGWButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.DragOnGWButton.setEnabled(True)
        self.DragOnGWButton.setMinimumSize(QtCore.QSize(40, 40))
        self.DragOnGWButton.setMaximumSize(QtCore.QSize(40, 40))
        self.DragOnGWButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.DragOnGWButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/move.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.DragOnGWButton.setIcon(icon2)
        self.DragOnGWButton.setIconSize(QtCore.QSize(15, 15))
        self.DragOnGWButton.setCheckable(True)
        self.DragOnGWButton.setChecked(False)
        self.DragOnGWButton.setProperty("clickCounter", 0)
        self.DragOnGWButton.setObjectName("DragOnGWButton")
        self.WorkspaceButtonGroup.addButton(self.DragOnGWButton)
        self.verticalLayout_7.addWidget(self.DragOnGWButton)
        self.ZoomInButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.ZoomInButton.setMinimumSize(QtCore.QSize(40, 40))
        self.ZoomInButton.setMaximumSize(QtCore.QSize(40, 40))
        self.ZoomInButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ZoomInButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/magnifying-glass-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ZoomInButton.setIcon(icon3)
        self.ZoomInButton.setIconSize(QtCore.QSize(17, 17))
        self.ZoomInButton.setObjectName("ZoomInButton")
        self.verticalLayout_7.addWidget(self.ZoomInButton)
        self.ZoomOutButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.ZoomOutButton.setMinimumSize(QtCore.QSize(40, 40))
        self.ZoomOutButton.setMaximumSize(QtCore.QSize(40, 40))
        self.ZoomOutButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ZoomOutButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/magnifying-glass.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ZoomOutButton.setIcon(icon4)
        self.ZoomOutButton.setIconSize(QtCore.QSize(17, 17))
        self.ZoomOutButton.setObjectName("ZoomOutButton")
        self.verticalLayout_7.addWidget(self.ZoomOutButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.gridLayout_5.addWidget(self.widget_8, 0, 0, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=self.workspace_container)
        self.graphicsView_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.graphicsView_2.setStyleSheet("border:0px;\n"
"")
        self.graphicsView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.graphicsView_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.graphicsView_2.setResizeAnchor(QtWidgets.QGraphicsView.ViewportAnchor.AnchorViewCenter)
        self.graphicsView_2.setViewportUpdateMode(QtWidgets.QGraphicsView.ViewportUpdateMode.MinimalViewportUpdate)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_5.addWidget(self.graphicsView_2, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.workspace_container, 1, 0, 1, 1)
        self.table_widget_container = QtWidgets.QWidget(parent=self.scene_widget)
        self.table_widget_container.setStyleSheet("")
        self.table_widget_container.setObjectName("table_widget_container")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.table_widget_container)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setHorizontalSpacing(0)
        self.gridLayout_24.setVerticalSpacing(2)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.bottom_table_widget = QtWidgets.QWidget(parent=self.table_widget_container)
        self.bottom_table_widget.setMinimumSize(QtCore.QSize(0, 200))
        self.bottom_table_widget.setObjectName("bottom_table_widget")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.bottom_table_widget)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.table_container = QtWidgets.QWidget(parent=self.bottom_table_widget)
        self.table_container.setToolTip("")
        self.table_container.setObjectName("table_container")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.table_container)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setSpacing(0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.TabletabWidget = QtWidgets.QTabWidget(parent=self.table_container)
        self.TabletabWidget.setStyleSheet("QTabWidget\n"
"{\n"
"      background: rgb(51, 51, 51);\n"
"    border: 0;\n"
"}\n"
"QTabWidget::pane {\n"
"    /*border-top: 1px solid rgba(129,129,129,50);*/\n"
"    top: 1px;\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"    color: grey;\n"
"    padding: 15 0 15 15;\n"
"    font: 700 10pt \"Consolas\";\n"
"    border: 2px;\n"
"    /*border-top-right-radius: 1px;*/\n"
"    border-left: 1px solid rgba(129, 129, 129, 50);\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"    background-color: rgb(45, 45, 45);\n"
"    border-bottom: 2px solid   rgb(0, 150, 255);\n"
"    /*border-bottom: 1px solid rgb(31,31,31);*/\n"
"    color: white;\n"
"}\n"
"QTabBar::tab:selected:hover{\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"QTabBar::tab:hover { \n"
"      background: rgb(45, 45, 45);\n"
"}\n"
"QTabWidget::tab-bar  {\n"
"left: 55px;\n"
"top: 1px;\n"
"}")
        self.TabletabWidget.setObjectName("TabletabWidget")
        self.gridLayout_27.addWidget(self.TabletabWidget, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.table_container, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.bottom_table_widget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.table_widget_container, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.scene_widget, 1, 2, 1, 1)
        self.WorkspaceMenuWidget = QtWidgets.QWidget(parent=WorkspaceDesignForm)
        self.WorkspaceMenuWidget.setMinimumSize(QtCore.QSize(285, 0))
        self.WorkspaceMenuWidget.setMaximumSize(QtCore.QSize(270, 16777215))
        self.WorkspaceMenuWidget.setStyleSheet("color:white;\n"
"background-color: rgb(31, 31, 31);\n"
"border-right:  1px solid rgba(129, 129, 129, 50);\n"
"border-left: 0;\n"
"/*border-top: 1px solid rgba(129, 129, 129, 50);*/")
        self.WorkspaceMenuWidget.setObjectName("WorkspaceMenuWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.WorkspaceMenuWidget)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.WorkspaceMenuWidget)
        self.stackedWidget.setStyleSheet("border: 0; margin: 0 0 0 0;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("padding: 5 5 5 5;\n"
"margin: 5 5 5 5;")
        self.page_5.setObjectName("page_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_4.setContentsMargins(0, 5, 0, -1)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_9 = QtWidgets.QWidget(parent=self.page_5)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget_9)
        self.label.setStyleSheet("QLabel {\n"
"    font: 700 11pt \"Consolas\";\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.workspaceEditSettingsButton = QtWidgets.QPushButton(parent=self.widget_9)
        self.workspaceEditSettingsButton.setMaximumSize(QtCore.QSize(45, 16777215))
        self.workspaceEditSettingsButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.workspaceEditSettingsButton.setTabletTracking(False)
        self.workspaceEditSettingsButton.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.workspaceEditSettingsButton.setStyleSheet("QPushButton {\n"
"    margin: 5 5 5 5;\n"
"    padding: 5 5 5 5;\n"
"    border-radius: 2px;\n"
"    background: transparent;\n"
"    /*background: rgb(25, 25, 25);*/\n"
"    /*border: 2px solid  rgb(35, 35, 35);*/\n"
"}\n"
"QPushButton:hover {\n"
"            background: rgb(72, 75, 75);\n"
"}\n"
"QPushButton:focus {\n"
"            background: rgb(75, 75, 75);\n"
"}")
        self.workspaceEditSettingsButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/setting.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.workspaceEditSettingsButton.setIcon(icon5)
        self.workspaceEditSettingsButton.setIconSize(QtCore.QSize(17, 17))
        self.workspaceEditSettingsButton.setCheckable(False)
        self.workspaceEditSettingsButton.setObjectName("workspaceEditSettingsButton")
        self.horizontalLayout.addWidget(self.workspaceEditSettingsButton)
        self.gridLayout_4.addWidget(self.widget_9, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.page_5)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_3.setStyleSheet("padding: 15 0 0 0;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_6.setStyleSheet("QLabel {font: 700 10pt \"Consolas\";color:     rgb(190, 190, 190);}")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.frame_15 = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_15.setStyleSheet("QFrame {\n"
"    margin: 0 0 0 0;\n"
"    padding: 10 0 0 0;\n"
"    border: 0 0 0 0;\n"
"}\n"
"QPushButton {\n"
"        border: 0px;\n"
"        font: 550 11pt \"Consolas\";\n"
"        text-align:left;\n"
"        color:     rgb(190, 190, 190);\n"
"        background:  rgb(40, 40, 40);\n"
"        margin: 0 0 0 0;\n"
"        border: 0px;\n"
"        padding: 5 10 5 10;\n"
"}\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"            color: white;\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        border-radius: 0px;\n"
"        border-left: 3px solid rgb(0, 150, 255);\n"
"        color: white;\n"
"}\n"
"QPushButton:unchecked  {\n"
"        border: 0px;\n"
"        background-color: transparent;\n"
"        color:     rgb(171, 171, 171);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.CreateWidgetButton = QtWidgets.QPushButton(parent=self.frame_15)
        self.CreateWidgetButton.setMinimumSize(QtCore.QSize(40, 40))
        self.CreateWidgetButton.setMaximumSize(QtCore.QSize(9999, 40))
        self.CreateWidgetButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CreateWidgetButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.CreateWidgetButton.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/widget.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.CreateWidgetButton.setIcon(icon6)
        self.CreateWidgetButton.setIconSize(QtCore.QSize(18, 19))
        self.CreateWidgetButton.setCheckable(True)
        self.CreateWidgetButton.setFlat(True)
        self.CreateWidgetButton.setObjectName("CreateWidgetButton")
        self.WorkspaceToolsButtonGroup = QtWidgets.QButtonGroup(WorkspaceDesignForm)
        self.WorkspaceToolsButtonGroup.setObjectName("WorkspaceToolsButtonGroup")
        self.WorkspaceToolsButtonGroup.addButton(self.CreateWidgetButton)
        self.verticalLayout_10.addWidget(self.CreateWidgetButton)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/pdf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(18, 19))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.WorkspaceToolsButtonGroup.addButton(self.pushButton)
        self.verticalLayout_10.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.frame_15)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_4.addWidget(self.widget_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.widget_list_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_list_page.sizePolicy().hasHeightForWidth())
        self.widget_list_page.setSizePolicy(sizePolicy)
        self.widget_list_page.setObjectName("widget_list_page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_list_page)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget_16 = QtWidgets.QWidget(parent=self.widget_list_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget.setStyleSheet("QTreeView {\n"
"    font: 550 12pt \"Consolas\";\n"
"    color: rgb(187, 187, 187);\n"
"}\n"
"QHeaderView::section { \n"
"    background-color: rgb(31,31,31);\n"
"    font: 12pt \"Consolas\";\n"
"    color: rgb(107, 107, 107);\n"
"    border:0;\n"
"margin: 0 0 0 15;\n"
"}\n"
"QTreeView::item{\n"
"padding: 0 0 3 0;\n"
"}\n"
"QTreeView::item:selected:active{\n"
"    background: rgb(0, 150, 255);\n"
"    color: white;\n"
"}\n"
"QTreeView::item:!has-children{\n"
"    color:  rgb(107, 107, 107);;\n"
"}\n"
"QTreeView::item:selected:!active {\n"
"    background: rgb(107, 107, 107);\n"
"    color: white;\n"
"}\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"    border-image: url(./resources/misc/vline.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(./resources/misc/branch-more.png);\n"
"\n"
"}\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"    border-image: url(./resources/misc/branch-end.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        border-image: none;\n"
"        image: url(./resources/misc/branch-closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"        border-image: none;\n"
"        image: url(./resources/misc/branch-open.png);\n"
"\n"
"}")
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.treeWidget.setIconSize(QtCore.QSize(16, 16))
        self.treeWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.treeWidget.setAutoExpandDelay(1)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setObjectName("treeWidget")
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 2))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        self.treeWidget.headerItem().setForeground(0, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setIcon(0, icon6)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/edit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item_0.setIcon(0, icon8)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item_0.setIcon(0, icon9)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/add-image.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item_0.setIcon(0, icon10)
        self.gridLayout_11.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_16, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.widget_list_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.WorkspaceMenuWidget, 1, 1, 1, 1)
        self.left_navbar = QtWidgets.QWidget(parent=WorkspaceDesignForm)
        self.left_navbar.setMinimumSize(QtCore.QSize(55, 0))
        self.left_navbar.setMaximumSize(QtCore.QSize(55, 16777215))
        self.left_navbar.setStyleSheet("color:white;\n"
"background-color: rgb(31, 31, 31);\n"
"margin: 0 0 0 0;\n"
"padding: 0 0 0 0;\n"
"border-right:  1px solid rgba(129, 129, 129, 50);\n"
"border-left: 0;")
        self.left_navbar.setObjectName("left_navbar")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.left_navbar)
        self.verticalLayout_11.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_17 = QtWidgets.QWidget(parent=self.left_navbar)
        self.widget_17.setStyleSheet("QWidget {border: 0;margin: 0 0 0 0;}\n"
"\n"
"QPushButton {\n"
"font: 570 10pt \"Consolas\";\n"
"color:     rgb(190, 190, 190);\n"
"margin: 0 0 0 0;\n"
"padding: 5,5,5,5;\n"
"}\n"
"QPushButton:hover {\n"
"            color: white;\n"
"            background:   rgb(40, 40, 40);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border-left: 3px solid rgb(0, 150, 255);\n"
"        border-radius: 0px;\n"
"        color: white;\n"
"        background:  rgb(40, 40, 40);\n"
"}\n"
"QPushButton:unchecked  {\n"
"        border: 0px;\n"
"        background-color: transparent;\n"
"        color:     rgb(171, 171, 171);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_17)
        self.widget_2.setMinimumSize(QtCore.QSize(54, 54))
        self.widget_2.setMaximumSize(QtCore.QSize(54, 54))
        self.widget_2.setStyleSheet("QWidget {border-bottom: 1px solid rgba(129, 129, 129, 50);}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_9.setContentsMargins(0, 2, 0, 2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.hideLeftSideTabButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.hideLeftSideTabButton.setMinimumSize(QtCore.QSize(45, 45))
        self.hideLeftSideTabButton.setMaximumSize(QtCore.QSize(45, 45))
        self.hideLeftSideTabButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.hideLeftSideTabButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.hideLeftSideTabButton.setStyleSheet("QPushButton {\n"
"    margin: 5 5 5 5;\n"
"    padding: 5 5 5 5;\n"
"    border-radius: 2px;\n"
"border: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background:   rgb(40, 40, 40);\n"
"}")
        self.hideLeftSideTabButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/back.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.hideLeftSideTabButton.setIcon(icon11)
        self.hideLeftSideTabButton.setIconSize(QtCore.QSize(17, 17))
        self.hideLeftSideTabButton.setObjectName("hideLeftSideTabButton")
        self.gridLayout_9.addWidget(self.hideLeftSideTabButton, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.widget_2)
        self.allToolsMenuButton = QtWidgets.QPushButton(parent=self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allToolsMenuButton.sizePolicy().hasHeightForWidth())
        self.allToolsMenuButton.setSizePolicy(sizePolicy)
        self.allToolsMenuButton.setMinimumSize(QtCore.QSize(54, 54))
        self.allToolsMenuButton.setMaximumSize(QtCore.QSize(54, 54))
        self.allToolsMenuButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.allToolsMenuButton.setStyleSheet("")
        self.allToolsMenuButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/grid.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.allToolsMenuButton.setIcon(icon12)
        self.allToolsMenuButton.setIconSize(QtCore.QSize(20, 20))
        self.allToolsMenuButton.setCheckable(True)
        self.allToolsMenuButton.setChecked(True)
        self.allToolsMenuButton.setAutoExclusive(False)
        self.allToolsMenuButton.setAutoDefault(False)
        self.allToolsMenuButton.setDefault(False)
        self.allToolsMenuButton.setObjectName("allToolsMenuButton")
        self.WorkspaceMenuButtonGroup = QtWidgets.QButtonGroup(WorkspaceDesignForm)
        self.WorkspaceMenuButtonGroup.setObjectName("WorkspaceMenuButtonGroup")
        self.WorkspaceMenuButtonGroup.addButton(self.allToolsMenuButton)
        self.verticalLayout_12.addWidget(self.allToolsMenuButton)
        self.widgetListMenuButton = QtWidgets.QPushButton(parent=self.widget_17)
        self.widgetListMenuButton.setMinimumSize(QtCore.QSize(54, 54))
        self.widgetListMenuButton.setMaximumSize(QtCore.QSize(54, 54))
        self.widgetListMenuButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.widgetListMenuButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/hierarchical-structure.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.widgetListMenuButton.setIcon(icon13)
        self.widgetListMenuButton.setIconSize(QtCore.QSize(25, 25))
        self.widgetListMenuButton.setCheckable(True)
        self.widgetListMenuButton.setObjectName("widgetListMenuButton")
        self.WorkspaceMenuButtonGroup.addButton(self.widgetListMenuButton)
        self.verticalLayout_12.addWidget(self.widgetListMenuButton)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.verticalLayout_11.addWidget(self.widget_17)
        self.gridLayout.addWidget(self.left_navbar, 0, 0, 2, 1)
        self.properties_right_panel = QtWidgets.QWidget(parent=WorkspaceDesignForm)
        self.properties_right_panel.setMinimumSize(QtCore.QSize(300, 0))
        self.properties_right_panel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.properties_right_panel.setStyleSheet("QWidget {\n"
"color:white;\n"
"background-color: rgb(31, 31, 31);\n"
"border-right:  0;\n"
"border-left: 1px solid rgba(129, 129, 129, 50);\n"
"border-top: 1px solid rgba(129, 129, 129, 50);}\n"
"\n"
"QLabel {\n"
"    font: 700 11pt \"Consolas\";\n"
"}")
        self.properties_right_panel.setObjectName("properties_right_panel")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.properties_right_panel)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setVerticalSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.properties_right_panel)
        self.stackedWidget_2.setStyleSheet("border:0px;")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setStyleSheet("border: 0px;")
        self.page_12.setObjectName("page_12")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_12)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.widget_10 = QtWidgets.QWidget(parent=self.page_12)
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_10.setStyleSheet("QWidget {\n"
"border:0px;\n"
"}\n"
"QLineEdit {\n"
"    background:  rgb(21, 21, 21);\n"
"    border-radius: 2px;\n"
"}\n"
"QLineEdit::text {\n"
"    font: 700 11pt \"Consolas\";\n"
"}\n"
"\n"
"QLabel {font: 700 10pt \"Consolas\";color:     rgb(190, 190, 190); padding:10 10 10 0; border: 0px;}")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.property_panel_object_properties = QtWidgets.QWidget(parent=self.widget_10)
        self.property_panel_object_properties.setStyleSheet("\n"
"QLabel {\n"
"border: 0;\n"
"padding: 10 10 10 10;\n"
" }")
        self.property_panel_object_properties.setObjectName("property_panel_object_properties")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.property_panel_object_properties)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.widget_13 = QtWidgets.QWidget(parent=self.property_panel_object_properties)
        self.widget_13.setStyleSheet("QWidget {padding: 5 5 5 5; border: 0px;}")
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtWidgets.QLabel(parent=self.widget_13)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit:focus{border:1px solid rgb(0, 150, 255);}")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_5.addWidget(self.lineEdit_7)
        self.gridLayout_19.addWidget(self.widget_13, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.property_panel_object_properties)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"text-align:left;\n"
"margin: 0 0 0 0;\n"
"padding: 5 5 5 5;\n"
"border: 0px;\n"
"background-color:   rgb(40, 40, 40);\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/misc/branch-closed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon14.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/misc/branch-open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_2.setIcon(icon14)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_19.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.property_panel_object_properties, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 7, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_10)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_7.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget_5)
        self.textEdit.setStyleSheet("\n"
"QTextEdit {\n"
"background:  rgb(21, 21, 21);\n"
"margin: 0 0 0 0;\n"
"}\n"
"\n"
"QTextEdit::focus {\n"
"border:1px solid rgb(0, 150, 255); }\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_7.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.widget_5, 6, 0, 1, 1)
        self.property_panel_header = QtWidgets.QWidget(parent=self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.property_panel_header.sizePolicy().hasHeightForWidth())
        self.property_panel_header.setSizePolicy(sizePolicy)
        self.property_panel_header.setMinimumSize(QtCore.QSize(0, 0))
        self.property_panel_header.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.property_panel_header.setStyleSheet("")
        self.property_panel_header.setObjectName("property_panel_header")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.property_panel_header)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setHorizontalSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.widget_11 = QtWidgets.QWidget(parent=self.property_panel_header)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 54))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 54))
        self.widget_11.setStyleSheet("background:   rgb(40, 40, 40);")
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_18.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_3.setStyleSheet("QLabel {font: 700 10pt \"Consolas\";color:     rgb(190, 190, 190); padding:10 0 10 0; border: 0px;}")
        self.label_3.setObjectName("label_3")
        self.gridLayout_18.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget_11, 0, 0, 1, 2)
        self.gridLayout_8.addWidget(self.property_panel_header, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"text-align:left;\n"
"margin: 0 0 0 0;\n"
"padding: 5 5 5 5;\n"
"border: 0px;\n"
"background-color:   rgb(40, 40, 40);\n"
"}")
        self.pushButton_4.setIcon(icon14)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setChecked(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_8.addWidget(self.pushButton_4, 5, 0, 1, 1)
        self.property_geometry_widget_main = QtWidgets.QWidget(parent=self.widget_10)
        self.property_geometry_widget_main.setMinimumSize(QtCore.QSize(0, 0))
        self.property_geometry_widget_main.setStyleSheet("")
        self.property_geometry_widget_main.setObjectName("property_geometry_widget_main")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.property_geometry_widget_main)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.widget_14 = QtWidgets.QWidget(parent=self.property_geometry_widget_main)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.property_geometry_widget = QtWidgets.QWidget(parent=self.widget_14)
        self.property_geometry_widget.setStyleSheet("QWidget {padding: 5 5 5 5; border: 0px;}")
        self.property_geometry_widget.setObjectName("property_geometry_widget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.property_geometry_widget)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setHorizontalSpacing(0)
        self.gridLayout_15.setVerticalSpacing(5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.property_panel_widget_properties = QtWidgets.QWidget(parent=self.property_geometry_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.property_panel_widget_properties.sizePolicy().hasHeightForWidth())
        self.property_panel_widget_properties.setSizePolicy(sizePolicy)
        self.property_panel_widget_properties.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.property_panel_widget_properties.setStyleSheet("QWidget {border: 0px;}\n"
"\n"
"QLabel {\n"
"border: 0;\n"
"padding: 10 10 10 10;\n"
" }")
        self.property_panel_widget_properties.setObjectName("property_panel_widget_properties")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.property_panel_widget_properties)
        self.gridLayout_14.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.widget_19 = QtWidgets.QWidget(parent=self.property_panel_widget_properties)
        self.widget_19.setStyleSheet("QWidget {padding: 5 5 5 5; border: 0px;}")
        self.widget_19.setObjectName("widget_19")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.widget_19)
        self.gridLayout_22.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_22.setHorizontalSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget_19)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit:focus{border:1px solid rgb(0, 150, 255);}")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_22.addWidget(self.lineEdit_2, 1, 3, 1, 1)
        self.x_lineEdit = QtWidgets.QLineEdit(parent=self.widget_19)
        self.x_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.x_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        self.x_lineEdit.setFont(font)
        self.x_lineEdit.setStyleSheet("QLineEdit:focus{border:1px solid rgb(0, 150, 255);}")
        self.x_lineEdit.setClearButtonEnabled(True)
        self.x_lineEdit.setObjectName("x_lineEdit")
        self.gridLayout_22.addWidget(self.x_lineEdit, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_19)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit:focus{border:1px solid rgb(0, 150, 255);}")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_22.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.y_lineEdit = QtWidgets.QLineEdit(parent=self.widget_19)
        self.y_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.y_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        self.y_lineEdit.setFont(font)
        self.y_lineEdit.setStyleSheet("QLineEdit:focus{border:1px solid rgb(0, 150, 255);}")
        self.y_lineEdit.setClearButtonEnabled(True)
        self.y_lineEdit.setObjectName("y_lineEdit")
        self.gridLayout_22.addWidget(self.y_lineEdit, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget_19)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_22.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget_19)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_22.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.widget_19)
        self.label_8.setObjectName("label_8")
        self.gridLayout_22.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_19)
        self.label_7.setObjectName("label_7")
        self.gridLayout_22.addWidget(self.label_7, 1, 0, 1, 1)
        self.gridLayout_14.addWidget(self.widget_19, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.property_panel_widget_properties, 1, 0, 1, 2)
        self.gridLayout_21.addWidget(self.property_geometry_widget, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.widget_14, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.property_geometry_widget_main)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"text-align:left;\n"
"margin: 0 0 0 0;\n"
"padding: 5 5 5 5;\n"
"border: 0px;\n"
"background-color:   rgb(40, 40, 40);\n"
"}")
        self.pushButton_3.setIcon(icon14)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setChecked(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_20.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.property_geometry_widget_main, 4, 0, 1, 1)
        self.gridLayout_16.addWidget(self.widget_10, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setStyleSheet("border:0px;")
        self.page_13.setObjectName("page_13")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.page_13)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.widget_6 = QtWidgets.QWidget(parent=self.page_13)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_6.setStyleSheet("border:0px;")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_2.setStyleSheet("border:0px;color: rgb(187, 187, 187);")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_23.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.widget_6, 1, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(parent=self.page_13)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 54))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 54))
        self.widget_7.setStyleSheet("QWidget {background:   rgb(40, 40, 40);}\n"
"QLabel {font: 700 10pt \"Consolas\";color:     rgb(190, 190, 190); padding:10 0 10 0; border: 0px;}")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.gridLayout_17.addWidget(self.widget_7, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_13)
        self.gridLayout_6.addWidget(self.stackedWidget_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.properties_right_panel, 1, 3, 1, 1)
        self.widget = QtWidgets.QWidget(parent=WorkspaceDesignForm)
        self.widget.setMinimumSize(QtCore.QSize(55, 0))
        self.widget.setMaximumSize(QtCore.QSize(55, 16777215))
        self.widget.setStyleSheet("color:white;\n"
"background-color: rgb(31, 31, 31);\n"
"margin: 0 0 0 0;\n"
"padding: 0 0 0 0;\n"
"border-left:  1px solid rgba(129, 129, 129, 50);\n"
"border-right: 0;\n"
"/*border-top: 1px solid rgba(129, 129, 129, 50);*/")
        self.widget.setObjectName("widget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_12.setContentsMargins(1, 0, 0, 1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_18 = QtWidgets.QWidget(parent=self.widget)
        self.widget_18.setStyleSheet("QWidget {border: 0;margin: 0 0 0 0;}\n"
"\n"
"QPushButton {\n"
"font: 570 10pt \"Consolas\";\n"
"color:     rgb(190, 190, 190);\n"
"margin: 0 0 0 0;\n"
"padding: 5,5,5,5;\n"
"}\n"
"QPushButton:hover {\n"
"            color: white;\n"
"            background:   rgb(40, 40, 40);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border-right: 4px solid rgb(0, 150, 255);\n"
"        border-radius: 0px;\n"
"        color: white;\n"
"        background:  rgb(40, 40, 40);\n"
"}\n"
"QPushButton:unchecked  {\n"
"        border: 0px;\n"
"        background-color: transparent;\n"
"        color:     rgb(171, 171, 171);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_properites_panel_button = QtWidgets.QPushButton(parent=self.widget_18)
        self.widget_properites_panel_button.setEnabled(True)
        self.widget_properites_panel_button.setMinimumSize(QtCore.QSize(54, 54))
        self.widget_properites_panel_button.setMaximumSize(QtCore.QSize(54, 54))
        self.widget_properites_panel_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.widget_properites_panel_button.setStyleSheet("")
        self.widget_properites_panel_button.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/properties.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.widget_properites_panel_button.setIcon(icon15)
        self.widget_properites_panel_button.setIconSize(QtCore.QSize(30, 30))
        self.widget_properites_panel_button.setCheckable(True)
        self.widget_properites_panel_button.setChecked(False)
        self.widget_properites_panel_button.setObjectName("widget_properites_panel_button")
        self.verticalLayout.addWidget(self.widget_properites_panel_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_18)
        self.pushButton_5.setMinimumSize(QtCore.QSize(54, 54))
        self.pushButton_5.setMaximumSize(QtCore.QSize(54, 54))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/layout_bottom.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon16.addPixmap(QtGui.QPixmap(".\\src\\ui\\../../resources/icons/layout_filled_bottom.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_5.setIcon(icon16)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setChecked(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.gridLayout_12.addWidget(self.widget_18, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 1, 4, 1, 1)

        self.retranslateUi(WorkspaceDesignForm)
        self.TabletabWidget.setCurrentIndex(-1)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(1)
        self.SelectButton.clicked['bool'].connect(WorkspaceDesignForm.handle_scene_select_mode) # type: ignore
        self.DeleteWidgetButton.toggled['bool'].connect(WorkspaceDesignForm.handle_scene_delete_mode) # type: ignore
        self.ZoomInButton.clicked.connect(WorkspaceDesignForm.handle_scene_zoom_in) # type: ignore
        self.DragOnGWButton.toggled['bool'].connect(WorkspaceDesignForm.handle_scene_drag_mode) # type: ignore
        self.ZoomOutButton.clicked.connect(WorkspaceDesignForm.handle_scene_zoom_out) # type: ignore
        self.hideLeftSideTabButton.clicked['bool'].connect(WorkspaceDesignForm.handle_left_menu_tab_visibility) # type: ignore
        self.workspaceEditSettingsButton.clicked.connect(WorkspaceDesignForm.handle_edit_settings_context_menu) # type: ignore
        self.WorkspaceMenuButtonGroup.idToggled['int','bool'].connect(self.stackedWidget.setCurrentIndex) # type: ignore
        self.allToolsMenuButton.clicked['bool'].connect(WorkspaceDesignForm.handle_menu_widget_visibility) # type: ignore
        self.widgetListMenuButton.clicked['bool'].connect(WorkspaceDesignForm.handle_menu_widget_visibility) # type: ignore
        self.widget_properites_panel_button.clicked['bool'].connect(WorkspaceDesignForm.handle_properties_widget_visibility) # type: ignore
        self.pushButton_2.toggled['bool'].connect(self.widget_13.setVisible) # type: ignore
        self.pushButton_3.toggled['bool'].connect(self.widget_14.setVisible) # type: ignore
        self.pushButton_4.toggled['bool'].connect(self.widget_5.setVisible) # type: ignore
        self.CreateWidgetButton.clicked['bool'].connect(WorkspaceDesignForm.handle_create_widget_on_scene) # type: ignore
        self.pushButton_5.toggled['bool'].connect(WorkspaceDesignForm.toggle_bottom_panel) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WorkspaceDesignForm)

    def retranslateUi(self, WorkspaceDesignForm):
        _translate = QtCore.QCoreApplication.translate
        WorkspaceDesignForm.setWindowTitle(_translate("WorkspaceDesignForm", "Form"))
        self.SelectButton.setToolTip(_translate("WorkspaceDesignForm", "Select:\n"
"Enable to select widgets."))
        self.DeleteWidgetButton.setToolTip(_translate("WorkspaceDesignForm", "Delete:\n"
"Click to delete the selected widget."))
        self.DragOnGWButton.setToolTip(_translate("WorkspaceDesignForm", "Move:\n"
"Click to navigate within the scene"))
        self.ZoomInButton.setToolTip(_translate("WorkspaceDesignForm", "Zoom in\n"
"Click here to zoom in."))
        self.ZoomOutButton.setToolTip(_translate("WorkspaceDesignForm", "Zoom out\n"
"Click here to zoom out."))
        self.label.setText(_translate("WorkspaceDesignForm", "All Tools"))
        self.label_6.setText(_translate("WorkspaceDesignForm", "ADD CONTENT"))
        self.CreateWidgetButton.setToolTip(_translate("WorkspaceDesignForm", "New:\n"
"Click to add a new widget."))
        self.CreateWidgetButton.setText(_translate("WorkspaceDesignForm", " Create New Widget"))
        self.pushButton.setText(_translate("WorkspaceDesignForm", " Create PDF"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("WorkspaceDesignForm", "EXPLORER"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("WorkspaceDesignForm", "Widget"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("WorkspaceDesignForm", "Text"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("WorkspaceDesignForm", "Other"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("WorkspaceDesignForm", "Image"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.widgetListMenuButton.setToolTip(_translate("WorkspaceDesignForm", "Shows all the widget on the scene in Tree View"))
        self.label_17.setText(_translate("WorkspaceDesignForm", "Name"))
        self.lineEdit_7.setPlaceholderText(_translate("WorkspaceDesignForm", "MyObject"))
        self.pushButton_2.setText(_translate("WorkspaceDesignForm", "OBJECT"))
        self.label_3.setText(_translate("WorkspaceDesignForm", "PROPERTY EDITOR"))
        self.pushButton_4.setText(_translate("WorkspaceDesignForm", "QSS"))
        self.lineEdit_2.setPlaceholderText(_translate("WorkspaceDesignForm", "0"))
        self.x_lineEdit.setPlaceholderText(_translate("WorkspaceDesignForm", "0"))
        self.lineEdit.setPlaceholderText(_translate("WorkspaceDesignForm", "0"))
        self.y_lineEdit.setPlaceholderText(_translate("WorkspaceDesignForm", "0"))
        self.label_5.setText(_translate("WorkspaceDesignForm", "Y"))
        self.label_4.setText(_translate("WorkspaceDesignForm", "X"))
        self.label_8.setText(_translate("WorkspaceDesignForm", "Height"))
        self.label_7.setText(_translate("WorkspaceDesignForm", "Width"))
        self.pushButton_3.setText(_translate("WorkspaceDesignForm", "WIDGET GEOMETRY"))
        self.label_2.setText(_translate("WorkspaceDesignForm", " <center> Please select a widget from the widget explorer <br/> <center>----- or ----- <br/> <center> use the select tool to choose the desired widget you wish to modify."))
        self.label_9.setText(_translate("WorkspaceDesignForm", "PROPERTY EDITOR"))
        self.pushButton_5.setToolTip(_translate("WorkspaceDesignForm", "Toggle Bottom Panel"))
