# Form implementation generated from reading ui file 'ui/workspaceDesignFomr.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WorkspaceDesignForm(object):
    def setupUi(self, WorkspaceDesignForm):
        WorkspaceDesignForm.setObjectName("WorkspaceDesignForm")
        WorkspaceDesignForm.resize(1256, 808)
        WorkspaceDesignForm.setStyleSheet("margin: 0 0 0 0;")
        self.gridLayout = QtWidgets.QGridLayout(WorkspaceDesignForm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.WorkspaceMenuWidget = QtWidgets.QWidget(parent=WorkspaceDesignForm)
        self.WorkspaceMenuWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.WorkspaceMenuWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.WorkspaceMenuWidget.setStyleSheet("color:white;\n"
"background-color: rgb(51, 51, 51);\n"
"border-right:  1px solid grey;\n"
"border-left: 0;\n"
"border-bottom: 0;\n"
"border-top: 0;")
        self.WorkspaceMenuWidget.setObjectName("WorkspaceMenuWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.WorkspaceMenuWidget)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.WorkspaceMenuWidget)
        self.widget.setStyleSheet("border: 0;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../../resources/icons/back.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.widget, 1, 1, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.WorkspaceMenuWidget)
        self.stackedWidget.setStyleSheet("border: 0;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_3 = QtWidgets.QWidget(parent=self.page_5)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_3.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 500 10pt \"Arial\";\n"
"        height: 40px;\n"
"        text-align:left;\n"
"        padding: 5 5 5 5;\n"
"        color:     rgb(190, 190, 190)\n"
"}\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"            color: white;\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        border-radius: 0px;\n"
"        border-left: 5px solid rgb(63, 101, 255);\n"
"        color: white;\n"
"}\n"
"QPushButton:unchecked  {\n"
"        border: 0px;\n"
"        background-color: transparent;\n"
"        color:     rgb(171, 171, 171);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}\n"
"QWidget {\n"
"border: 0;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CreateWidgetButton = QtWidgets.QPushButton(parent=self.widget_3)
        self.CreateWidgetButton.setMinimumSize(QtCore.QSize(40, 40))
        self.CreateWidgetButton.setMaximumSize(QtCore.QSize(9999, 40))
        self.CreateWidgetButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CreateWidgetButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.CreateWidgetButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/../../resources/icons/widget.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.CreateWidgetButton.setIcon(icon1)
        self.CreateWidgetButton.setIconSize(QtCore.QSize(18, 19))
        self.CreateWidgetButton.setCheckable(True)
        self.CreateWidgetButton.setFlat(True)
        self.CreateWidgetButton.setObjectName("CreateWidgetButton")
        self.WorkspaceToolsButtonGroup = QtWidgets.QButtonGroup(WorkspaceDesignForm)
        self.WorkspaceToolsButtonGroup.setObjectName("WorkspaceToolsButtonGroup")
        self.WorkspaceToolsButtonGroup.addButton(self.CreateWidgetButton)
        self.verticalLayout_2.addWidget(self.CreateWidgetButton)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/../../resources/icons/pdf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(18, 19))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.WorkspaceToolsButtonGroup.addButton(self.pushButton)
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.widget_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_7 = QtWidgets.QWidget(parent=self.page_6)
        self.widget_7.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 500 10pt \"Arial\";\n"
"        height: 40px;\n"
"        text-align:left;\n"
"        padding: 5 5 5 5;\n"
"        color:     rgb(190, 190, 190)\n"
"}\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"            color: white;\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        border-radius: 0px;\n"
"        border-left: 5px solid rgb(63, 101, 255);\n"
"        color: white;\n"
"}\n"
"QPushButton:unchecked  {\n"
"        border: 0px;\n"
"        background-color: transparent;\n"
"        color:     rgb(171, 171, 171);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}\n"
"QWidget {\n"
"border: 0;\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CreateWidgetButton_2 = QtWidgets.QPushButton(parent=self.widget_7)
        self.CreateWidgetButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.CreateWidgetButton_2.setMaximumSize(QtCore.QSize(9999, 40))
        self.CreateWidgetButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CreateWidgetButton_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.CreateWidgetButton_2.setStyleSheet("")
        self.CreateWidgetButton_2.setIcon(icon1)
        self.CreateWidgetButton_2.setIconSize(QtCore.QSize(18, 19))
        self.CreateWidgetButton_2.setCheckable(True)
        self.CreateWidgetButton_2.setFlat(True)
        self.CreateWidgetButton_2.setObjectName("CreateWidgetButton_2")
        self.verticalLayout_3.addWidget(self.CreateWidgetButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayout_6.addWidget(self.widget_7, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.WorkspaceMenuWidget, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=WorkspaceDesignForm)
        self.widget_2.setEnabled(True)
        self.widget_2.setMinimumSize(QtCore.QSize(495, 601))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setStyleSheet("background-color: rgb(20, 20, 20); ")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_8.setMaximumSize(QtCore.QSize(55, 210))
        self.widget_8.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border: 0px;")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SelectButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.SelectButton.setMinimumSize(QtCore.QSize(40, 40))
        self.SelectButton.setMaximumSize(QtCore.QSize(40, 40))
        self.SelectButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SelectButton.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 12pt;\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        background-color: rgb(63, 101, 255);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.SelectButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/../../resources/icons/cursor.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.SelectButton.setIcon(icon3)
        self.SelectButton.setCheckable(True)
        self.SelectButton.setChecked(False)
        self.SelectButton.setAutoExclusive(True)
        self.SelectButton.setObjectName("SelectButton")
        self.WorkspaceButtonGroup = QtWidgets.QButtonGroup(WorkspaceDesignForm)
        self.WorkspaceButtonGroup.setObjectName("WorkspaceButtonGroup")
        self.WorkspaceButtonGroup.addButton(self.SelectButton)
        self.verticalLayout_7.addWidget(self.SelectButton)
        self.line_8 = QtWidgets.QFrame(parent=self.widget_8)
        self.line_8.setStyleSheet("background-color: rgba(129, 129, 129, 50);\n"
"border: 0px;\n"
"margin: 5, 5, 5, 5;")
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_7.addWidget(self.line_8)
        self.DeleteWidgetButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.DeleteWidgetButton.setMinimumSize(QtCore.QSize(40, 40))
        self.DeleteWidgetButton.setMaximumSize(QtCore.QSize(40, 40))
        self.DeleteWidgetButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.DeleteWidgetButton.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 12pt;\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        background-color: rgb(63, 101, 255);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.DeleteWidgetButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui/../../resources/icons/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.DeleteWidgetButton.setIcon(icon4)
        self.DeleteWidgetButton.setIconSize(QtCore.QSize(15, 15))
        self.DeleteWidgetButton.setCheckable(True)
        self.DeleteWidgetButton.setChecked(False)
        self.DeleteWidgetButton.setObjectName("DeleteWidgetButton")
        self.WorkspaceButtonGroup.addButton(self.DeleteWidgetButton)
        self.verticalLayout_7.addWidget(self.DeleteWidgetButton)
        self.line_5 = QtWidgets.QFrame(parent=self.widget_8)
        self.line_5.setStyleSheet("background-color: rgba(129, 129, 129, 50);\n"
"border: 0px;\n"
"margin: 5, 5, 5, 5;")
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_7.addWidget(self.line_5)
        self.DragOnGWButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.DragOnGWButton.setEnabled(True)
        self.DragOnGWButton.setMinimumSize(QtCore.QSize(40, 40))
        self.DragOnGWButton.setMaximumSize(QtCore.QSize(40, 40))
        self.DragOnGWButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.DragOnGWButton.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 12pt;\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        background-color: rgb(63, 101, 255);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.DragOnGWButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui/../../resources/icons/move.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.DragOnGWButton.setIcon(icon5)
        self.DragOnGWButton.setIconSize(QtCore.QSize(15, 15))
        self.DragOnGWButton.setCheckable(True)
        self.DragOnGWButton.setChecked(False)
        self.DragOnGWButton.setProperty("clickCounter", 0)
        self.DragOnGWButton.setObjectName("DragOnGWButton")
        self.WorkspaceButtonGroup.addButton(self.DragOnGWButton)
        self.verticalLayout_7.addWidget(self.DragOnGWButton)
        self.ZoomInButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.ZoomInButton.setMinimumSize(QtCore.QSize(40, 40))
        self.ZoomInButton.setMaximumSize(QtCore.QSize(40, 40))
        self.ZoomInButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ZoomInButton.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 12pt;\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"        }\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.ZoomInButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ui/../../resources/icons/magnifying-glass-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ZoomInButton.setIcon(icon6)
        self.ZoomInButton.setIconSize(QtCore.QSize(17, 17))
        self.ZoomInButton.setObjectName("ZoomInButton")
        self.verticalLayout_7.addWidget(self.ZoomInButton)
        self.ZoomOutButton = QtWidgets.QPushButton(parent=self.widget_8)
        self.ZoomOutButton.setMinimumSize(QtCore.QSize(40, 40))
        self.ZoomOutButton.setMaximumSize(QtCore.QSize(40, 40))
        self.ZoomOutButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ZoomOutButton.setStyleSheet("QPushButton {\n"
"        border: 0px;\n"
"        font: 12pt;\n"
"        }\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"        }\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.ZoomOutButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ui/../../resources/icons/magnifying-glass.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ZoomOutButton.setIcon(icon7)
        self.ZoomOutButton.setIconSize(QtCore.QSize(17, 17))
        self.ZoomOutButton.setObjectName("ZoomOutButton")
        self.verticalLayout_7.addWidget(self.ZoomOutButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.gridLayout_5.addWidget(self.widget_8, 0, 0, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=self.widget_4)
        self.graphicsView_2.setStyleSheet("border:0px;\n"
"")
        self.graphicsView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.graphicsView_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.graphicsView_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.graphicsView_2.setResizeAnchor(QtWidgets.QGraphicsView.ViewportAnchor.NoAnchor)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_5.addWidget(self.graphicsView_2, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 1, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(parent=WorkspaceDesignForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_5.setStyleSheet("color:white;\n"
"background-color: rgb(51, 51, 51);\n"
"border-left: 0;\n"
"border-right: 0;\n"
"border-bottom: 1px solid grey;\n"
"border-top: 0;")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_7.setContentsMargins(5, 2, 5, 2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_6.setStyleSheet("QWidget {border: 0;}\n"
"\n"
"QPushButton {\n"
"font: 630 10pt \"Arial\";\n"
"color:     rgb(190, 190, 190);\n"
"padding: 5 0 5 0;\n"
"margin: 5 5 5 5;\n"
"}\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"            color: white;\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        border-radius: 0px;\n"
"        border-bottom: 1px solid white;\n"
"        color: white;\n"
"}\n"
"QPushButton:unchecked  {\n"
"        border: 0px;\n"
"        background-color: transparent;\n"
"        color:     rgb(171, 171, 171);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.allToolsMenuButton = QtWidgets.QPushButton(parent=self.widget_6)
        self.allToolsMenuButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.allToolsMenuButton.setStyleSheet("\n"
"QPushButton {\n"
"font: 630 10pt \"Arial\";\n"
"color:     rgb(190, 190, 190);\n"
"padding: 5 0 5 0;\n"
"}\n"
"QPushButton:hover {\n"
"            background: rgb(55, 55, 55);\n"
"            color: white;\n"
"        }\n"
"QPushButton:checked  {\n"
"        border: 0px;\n"
"        border-radius: 0px;\n"
"        border-bottom: 1px solid white;\n"
"        color: white;\n"
"}\n"
"QPushButton:unchecked  {\n"
"        border: 0px;\n"
"        background-color: transparent;\n"
"        color:     rgb(171, 171, 171);\n"
"}\n"
"QToolTip{ \n"
"        font: 12pt;\n"
"        color: rgb(100, 100, 100);\n"
"}")
        self.allToolsMenuButton.setIconSize(QtCore.QSize(25, 25))
        self.allToolsMenuButton.setCheckable(True)
        self.allToolsMenuButton.setChecked(True)
        self.allToolsMenuButton.setAutoExclusive(False)
        self.allToolsMenuButton.setAutoDefault(False)
        self.allToolsMenuButton.setDefault(False)
        self.allToolsMenuButton.setObjectName("allToolsMenuButton")
        self.WorkspaceMenuButtonGroup = QtWidgets.QButtonGroup(WorkspaceDesignForm)
        self.WorkspaceMenuButtonGroup.setObjectName("WorkspaceMenuButtonGroup")
        self.WorkspaceMenuButtonGroup.addButton(self.allToolsMenuButton)
        self.horizontalLayout_2.addWidget(self.allToolsMenuButton)
        self.createMenuButton = QtWidgets.QPushButton(parent=self.widget_6)
        self.createMenuButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.createMenuButton.setCheckable(True)
        self.createMenuButton.setChecked(False)
        self.createMenuButton.setAutoExclusive(True)
        self.createMenuButton.setAutoDefault(False)
        self.createMenuButton.setDefault(False)
        self.createMenuButton.setObjectName("createMenuButton")
        self.WorkspaceMenuButtonGroup.addButton(self.createMenuButton)
        self.horizontalLayout_2.addWidget(self.createMenuButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_7.addWidget(self.widget_6, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_5, 0, 0, 1, 2)

        self.retranslateUi(WorkspaceDesignForm)
        self.stackedWidget.setCurrentIndex(0)
        self.SelectButton.clicked['bool'].connect(WorkspaceDesignForm.HandleSelectMode) # type: ignore
        self.DeleteWidgetButton.toggled['bool'].connect(WorkspaceDesignForm.HandleDeleteMode) # type: ignore
        self.ZoomInButton.clicked.connect(WorkspaceDesignForm.HandleZoomIn) # type: ignore
        self.DragOnGWButton.toggled['bool'].connect(WorkspaceDesignForm.HandleDragMode) # type: ignore
        self.ZoomOutButton.clicked.connect(WorkspaceDesignForm.HandleZoomOut) # type: ignore
        self.CreateWidgetButton.clicked['bool'].connect(WorkspaceDesignForm.HandleCreateWidgetMode) # type: ignore
        self.createMenuButton.clicked['bool'].connect(WorkspaceDesignForm.HandleMenuWidgetVisibility) # type: ignore
        self.WorkspaceMenuButtonGroup.idToggled['int','bool'].connect(self.stackedWidget.setCurrentIndex) # type: ignore
        self.pushButton_2.clicked['bool'].connect(self.WorkspaceMenuWidget.setVisible) # type: ignore
        self.allToolsMenuButton.clicked['bool'].connect(WorkspaceDesignForm.HandleMenuWidgetVisibility) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WorkspaceDesignForm)

    def retranslateUi(self, WorkspaceDesignForm):
        _translate = QtCore.QCoreApplication.translate
        WorkspaceDesignForm.setWindowTitle(_translate("WorkspaceDesignForm", "Form"))
        self.CreateWidgetButton.setToolTip(_translate("WorkspaceDesignForm", "New:\n"
"Click to add a new widget."))
        self.CreateWidgetButton.setText(_translate("WorkspaceDesignForm", "  Create New Widget"))
        self.pushButton.setText(_translate("WorkspaceDesignForm", "  Create PDF"))
        self.CreateWidgetButton_2.setToolTip(_translate("WorkspaceDesignForm", "New:\n"
"Click to add a new widget."))
        self.CreateWidgetButton_2.setText(_translate("WorkspaceDesignForm", "  Create New Widget"))
        self.SelectButton.setToolTip(_translate("WorkspaceDesignForm", "Select:\n"
"Enable to select widgets."))
        self.DeleteWidgetButton.setToolTip(_translate("WorkspaceDesignForm", "Delete:\n"
"Click to delete the selected widget."))
        self.DragOnGWButton.setToolTip(_translate("WorkspaceDesignForm", "Move:\n"
"Click to navigate within the scene"))
        self.ZoomInButton.setToolTip(_translate("WorkspaceDesignForm", "Zoom in\n"
"Click here to zoom in."))
        self.ZoomOutButton.setToolTip(_translate("WorkspaceDesignForm", "Zoom out\n"
"Click here to zoom out."))
        self.allToolsMenuButton.setText(_translate("WorkspaceDesignForm", " All Tools"))
        self.createMenuButton.setText(_translate("WorkspaceDesignForm", "Create"))
