# Form implementation generated from reading ui file 'ui/workspace_data_table.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(925, 432)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget_2.setStyleSheet("border-right: 1px solid rgb(41,41,41);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 430))
        self.scrollAreaWidgetContents.setStyleSheet("border-right: 0px;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setStyleSheet("border-right: 0px;")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_5.setStyleSheet("border-right: 0px;")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget_5)
        self.label.setStyleSheet("color: white; \n"
"border-right: 0px;\n"
"font: 700 10pt \"Consolas\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setStyleSheet("color: white; \n"
"border-right: 0px;\n"
"font: 700 10pt \"Consolas\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../../resources/icons/properties.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.scrollAreaWidgetContents)
        self.treeWidget.setStyleSheet("QTreeWidget {\n"
"    background-color: #1e1e1e;\n"
"    alternate-background-color: #222;\n"
"    color: #dcdcdc;\n"
"    border: 1px solid #333;\n"
"    padding: 5px;\n"
"    font: 11pt \"Consolas\";\n"
"}\n"
"\n"
"/* Sorok alap */\n"
"QTreeWidget::item {\n"
"    height: 28px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QTreeWidget::item:hover {\n"
"    background-color: #2b2b2b;\n"
"}\n"
"\n"
"/* Kijelölt sor */\n"
"QTreeWidget::item:selected {\n"
"    background-color: #3d6aff;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Kijelölt + hover */\n"
"QTreeWidget::item:selected:hover {\n"
"    background-color: #5278ff;\n"
"}\n"
"\n"
"/* Checkbox — ALAP (nincs kép, gyönyörű QSS kocka) */\n"
"QTreeWidget::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 3px;\n"
"    border: 1px solid #666;\n"
"    background: #222;\n"
"}\n"
"\n"
"/* Hover checkbox */\n"
"QTreeWidget::indicator:hover {\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"/* Unchecked */\n"
"QTreeWidget::indicator:unchecked {\n"
"    background: #2a2a2a;\n"
"}\n"
"\n"
"/* Checked */\n"
"QTreeWidget::indicator:checked {\n"
"    background-color: #3d6aff;\n"
"    border: 1px solid #3d6aff;\n"
"}\n"
"\n"
"/* CHECKBOX a kijelölt soron → világosabb legyen hogy látszódjon */\n"
"QTreeWidget::item:selected QTreeWidget::indicator {\n"
"    background: #eef1ff;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"/* CHECKED a kijelölt soron → kék maradjon de világosabb */\n"
"QTreeWidget::item:selected QTreeWidget::indicator:checked {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"/* Header */\n"
"QHeaderView::section {\n"
"    background-color: #2b2b2b;\n"
"    color: #dcdcdc;\n"
"    padding: 6px;\n"
"    font: bold 10pt \"Consolas\";\n"
"    border: 1px solid #3a3a3a;\n"
"}\n"
"\n"
"/* Scrollbar */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: #1e1e1e;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #3a3a3a;\n"
"    min-height: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #505050;\n"
"}\n"
"\n"
"QScrollBar::add-line,\n"
"QScrollBar::sub-line {\n"
"    background: none;\n"
"    height: 0px;\n"
"}\n"
"")
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_3.addWidget(self.treeWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget_2)
        self.TableContainer = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableContainer.sizePolicy().hasHeightForWidth())
        self.TableContainer.setSizePolicy(sizePolicy)
        self.TableContainer.setStyleSheet("")
        self.TableContainer.setObjectName("TableContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.TableContainer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout.addWidget(self.TableContainer)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.OpenFilterWidget) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Available Files"))
        self.pushButton.setText(_translate("Form", "Open Filters"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "File"))
        self.treeWidget.headerItem().setText(1, _translate("Form", "Selected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
